const BeheadingConfig = {
  baseCols: [
    { key: 'sampleNumber',   label: 'Sample Number'       },
    { key: 'section',        label: 'Section'             },
    { key: 'batchInfo',      label: 'Batch Info'          },
    { key: 'batchNumber',    label: 'Batch Number'        },
    { key: 'count',          label: 'Count'               },
    { key: 'quantity',       label: 'Quantity'            },
    { key: 'sampleSize',     label: 'Sample Size'         },
    { key: 'uniformity',     label: 'Uniformity'          },
    { key: 'photo',          label: 'Photo',         type: 'photo'    },
    { key: 'totalDefects',   label: 'Total Defects (gms)' },
    { key: 'finalResult',    label: 'Final Result',  type: 'passFail' },
    { key: 'correctiveAction', label: 'Corrective Action' },
  ],
  extraCols: [],
  valueCols: [
    { key: 'decomposition',    label: 'Decomposition (Spec)'        },
    { key: 'discoloration',    label: 'Discoloration (Spec)'        },
    { key: 'softShell',        label: 'Soft Shell (Spec)'           },
    { key: 'looseShell',       label: 'Loose Shell (Spec)'          },
    { key: 'blackTail',        label: 'Black Tail (Spec)'           },
    { key: 'blackSpots',       label: 'Black Spots (Spec)'          },
    { key: 'passFailSpec',     label: 'Pass/Fail (Spec)'            },
    { key: 'correctiveActionSpec', label: 'Corrective Action (Spec)' },
    { key: 'brokenDamaged',   label: 'Broken/Damaged (Spec)'       },
    { key: 'hangingMeat',     label: 'Hanging Meat/Neck Meat (Spec)' },
    { key: 'foreignMatter',   label: 'Foreign Matter (Spec)'        },
    { key: 'fungusParasites', label: 'Fungus/Parasites (Spec)'      },
    { key: 'presenceOfMetal', label: 'Presence of Metal'            },
  ],
  actionLabel: 'Action',
  data: {
    'pre-harvest': [
      {
        key: '1', sampleNumber: '42213', section: 'Beheading', batchInfo: '125-13c-12/14-3214',
        batchNumber: '125-65-3214', count: '12c', quantity: '64583', sampleSize: '12 gms',
        uniformity: '45', totalDefects: '12 gms -100%', finalResult: 'Pass', correctiveAction: 'Shrimp has Dark Spots',
        decomposition:       { value: 0.49, pass: true  },
        discoloration:       { value: 0.10, pass: false },
        softShell:           { value: 0.34, pass: true  },
        looseShell:          { value: 0.34, pass: true  },
        blackTail:           { value: 0.34, pass: true  },
        blackSpots:          { value: 0.10, pass: false },
        passFailSpec:        { value: 0.33, pass: true  },
        correctiveActionSpec: { value: 0.49, pass: true },
        brokenDamaged:       { value: 0.28, pass: false },
        hangingMeat:         { value: 0.49, pass: true  },
        foreignMatter:       { value: 0.34, pass: true  },
        fungusParasites:     { value: 4.62, pass: true  },
        presenceOfMetal:     { value: 1.45, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', sampleNumber: '42213', section: 'Beheading', batchInfo: '125-13c-12/14-3214',
        batchNumber: '234-76-5432', count: '16a', quantity: '12345', sampleSize: '8 gms',
        uniformity: '30', totalDefects: '8 gms -80%', finalResult: 'Pass', correctiveAction: 'Shrimp has Dark Spots',
        decomposition:       { value: 0.26, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShell:           { value: 0.26, pass: true  },
        looseShell:          { value: 0.34, pass: true  },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.10, pass: false },
        passFailSpec:        { value: 0.26, pass: true  },
        correctiveActionSpec: null,
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeat:         { value: 0.26, pass: true  },
        foreignMatter:       { value: 0.34, pass: true  },
        fungusParasites:     { value: 0.26, pass: true  },
        presenceOfMetal:     { value: 1.45, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '3', sampleNumber: '42213', section: 'Beheading', batchInfo: '125-13c-12/14-3214',
        batchNumber: '345-87-6543', count: '10b', quantity: '67890', sampleSize: '15 gms',
        uniformity: '50', totalDefects: '15 gms -90%', finalResult: 'Pass', correctiveAction: 'Shrimp has Dark Spots',
        decomposition:       { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        softShell:           { value: 0.34, pass: true  },
        looseShell:          { value: 0.22, pass: false },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.34, pass: true  },
        passFailSpec:        { value: 0.33, pass: true  },
        correctiveActionSpec: { value: 0.26, pass: true },
        brokenDamaged:       { value: 0.28, pass: false },
        hangingMeat:         null,
        foreignMatter:       { value: 0.34, pass: true  },
        fungusParasites:     { value: 0.26, pass: true  },
        presenceOfMetal:     { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4', sampleNumber: '42213', section: 'Beheading', batchInfo: '125-13c-12/14-3214',
        batchNumber: '456-98-7654', count: '14d', quantity: '24680', sampleSize: '20 gms',
        uniformity: '20', totalDefects: '20 gms -70%', finalResult: 'Pass', correctiveAction: 'Shrimp has Dark Spots',
        decomposition:       { value: 0.49, pass: true  },
        discoloration:       { value: 0.10, pass: false },
        softShell:           { value: 0.34, pass: true  },
        looseShell:          { value: 0.34, pass: true  },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.22, pass: false },
        passFailSpec:        { value: 0.33, pass: true  },
        correctiveActionSpec: null,
        brokenDamaged:       { value: 0.28, pass: false },
        hangingMeat:         { value: 0.22, pass: false },
        foreignMatter:       { value: 0.34, pass: true  },
        fungusParasites:     { value: 4.62, pass: true  },
        presenceOfMetal:     { value: 1.45, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '5', sampleNumber: '42213', section: 'Beheading', batchInfo: '125-13c-12/14-3214',
        batchNumber: '567-09-8765', count: '18e', quantity: '13579', sampleSize: '25 gms',
        uniformity: '15', totalDefects: '25 gms -60%', finalResult: 'Pass', correctiveAction: 'Shrimp has Dark Spots',
        decomposition:       { value: 0.26, pass: true  },
        discoloration:       { value: 0.10, pass: false },
        softShell:           { value: 0.22, pass: false },
        looseShell:          { value: 0.34, pass: true  },
        blackTail:           { value: 0.34, pass: true  },
        blackSpots:          { value: 0.10, pass: false },
        passFailSpec:        { value: 0.26, pass: true  },
        correctiveActionSpec: null,
        brokenDamaged:       { value: 0.28, pass: false },
        hangingMeat:         null,
        foreignMatter:       { value: 0.34, pass: true  },
        fungusParasites:     { value: 0.26, pass: true  },
        presenceOfMetal:     { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6', sampleNumber: '42213', section: 'Beheading', batchInfo: '125-13c-12/14-3214',
        batchNumber: '678-12-9876', count: '20f', quantity: '35790', sampleSize: '18 gms',
        uniformity: '35', totalDefects: '18 gms -75%', finalResult: 'Fail', correctiveAction: 'Black spots on tail',
        decomposition:       { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        softShell:           { value: 0.34, pass: true  },
        looseShell:          { value: 0.22, pass: false },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.34, pass: true  },
        passFailSpec:        { value: 0.33, pass: true  },
        correctiveActionSpec: { value: 0.26, pass: true },
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeat:         null,
        foreignMatter:       { value: 0.26, pass: true  },
        fungusParasites:     { value: 0.22, pass: false },
        presenceOfMetal:     { value: 1.45, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7', sampleNumber: '42213', section: 'Beheading', batchInfo: '125-13c-12/14-3214',
        batchNumber: '789-23-0987', count: '22g', quantity: '46801', sampleSize: '10 gms',
        uniformity: '40', totalDefects: '10 gms -85%', finalResult: 'Fail', correctiveAction: 'Loose shell detected',
        decomposition:       { value: 0.26, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShell:           { value: 0.22, pass: false },
        looseShell:          { value: 0.34, pass: true  },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.10, pass: false },
        passFailSpec:        { value: 0.26, pass: true  },
        correctiveActionSpec: null,
        brokenDamaged:       { value: 0.28, pass: false },
        hangingMeat:         { value: 0.34, pass: true  },
        foreignMatter:       { value: 0.26, pass: true  },
        fungusParasites:     { value: 4.62, pass: true  },
        presenceOfMetal:     { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
    ],
    'processing': [
      {
        key: '1', sampleNumber: '42214', section: 'Beheading', batchInfo: '136-13c-12/14-3215',
        batchNumber: '125-66-3215', count: '11c', quantity: '55432', sampleSize: '14 gms',
        uniformity: '42', totalDefects: '14 gms -95%', finalResult: 'Pass', correctiveAction: 'Clean batch',
        decomposition:       { value: 0.44, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShell:           { value: 0.34, pass: true  },
        looseShell:          { value: 0.34, pass: true  },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.22, pass: false },
        passFailSpec:        { value: 0.33, pass: true  },
        correctiveActionSpec: null,
        brokenDamaged:       { value: 0.26, pass: true  },
        hangingMeat:         null,
        foreignMatter:       { value: 0.34, pass: true  },
        fungusParasites:     { value: 0.26, pass: true  },
        presenceOfMetal:     { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', sampleNumber: '42214', section: 'Beheading', batchInfo: '136-13c-12/14-3215',
        batchNumber: '236-77-4321', count: '13b', quantity: '23456', sampleSize: '9 gms',
        uniformity: '28', totalDefects: '9 gms -78%', finalResult: 'Fail', correctiveAction: 'Decomposition noted',
        decomposition:       { value: 0.09, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        softShell:           { value: 0.22, pass: false },
        looseShell:          { value: 0.34, pass: true  },
        blackTail:           { value: 0.34, pass: true  },
        blackSpots:          { value: 0.10, pass: false },
        passFailSpec:        { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:       { value: 0.28, pass: false },
        hangingMeat:         null,
        foreignMatter:       { value: 0.26, pass: true  },
        fungusParasites:     { value: 0.34, pass: true  },
        presenceOfMetal:     { value: 1.45, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3', sampleNumber: '42214', section: 'Beheading', batchInfo: '136-13c-12/14-3215',
        batchNumber: '347-88-5432', count: '09d', quantity: '78012', sampleSize: '16 gms',
        uniformity: '48', totalDefects: '16 gms -92%', finalResult: 'Pass', correctiveAction: 'Good quality',
        decomposition:       { value: 0.49, pass: true  },
        discoloration:       { value: 0.10, pass: false },
        softShell:           { value: 0.34, pass: true  },
        looseShell:          { value: 0.26, pass: true  },
        blackTail:           { value: 0.34, pass: true  },
        blackSpots:          { value: 0.34, pass: true  },
        passFailSpec:        { value: 0.33, pass: true  },
        correctiveActionSpec: null,
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeat:         { value: 0.26, pass: true  },
        foreignMatter:       { value: 0.34, pass: true  },
        fungusParasites:     { value: 4.62, pass: true  },
        presenceOfMetal:     { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4', sampleNumber: '42214', section: 'Beheading', batchInfo: '136-13c-12/14-3215',
        batchNumber: '458-99-6543', count: '15e', quantity: '34567', sampleSize: '22 gms',
        uniformity: '22', totalDefects: '22 gms -68%', finalResult: 'Fail', correctiveAction: 'Discoloration found',
        decomposition:       { value: 0.22, pass: false },
        discoloration:       { value: 0.10, pass: false },
        softShell:           { value: 0.22, pass: false },
        looseShell:          { value: 0.34, pass: true  },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.10, pass: false },
        passFailSpec:        { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:       { value: 0.28, pass: false },
        hangingMeat:         null,
        foreignMatter:       { value: 0.26, pass: true  },
        fungusParasites:     { value: 0.22, pass: false },
        presenceOfMetal:     { value: 1.45, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5', sampleNumber: '42214', section: 'Beheading', batchInfo: '136-13c-12/14-3215',
        batchNumber: '569-00-7654', count: '17f', quantity: '45678', sampleSize: '27 gms',
        uniformity: '18', totalDefects: '27 gms -58%', finalResult: 'Pass', correctiveAction: 'Minimal defects',
        decomposition:       { value: 0.26, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShell:           { value: 0.34, pass: true  },
        looseShell:          { value: 0.22, pass: false },
        blackTail:           { value: 0.34, pass: true  },
        blackSpots:          { value: 0.34, pass: true  },
        passFailSpec:        { value: 0.33, pass: true  },
        correctiveActionSpec: null,
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeat:         null,
        foreignMatter:       { value: 0.34, pass: true  },
        fungusParasites:     { value: 4.62, pass: true  },
        presenceOfMetal:     { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6', sampleNumber: '42214', section: 'Beheading', batchInfo: '136-13c-12/14-3215',
        batchNumber: '670-11-8765', count: '19g', quantity: '56789', sampleSize: '19 gms',
        uniformity: '33', totalDefects: '19 gms -72%', finalResult: 'Fail', correctiveAction: 'Foreign matter present',
        decomposition:       { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        softShell:           { value: 0.22, pass: false },
        looseShell:          { value: 0.26, pass: true  },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.10, pass: false },
        passFailSpec:        { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:       { value: 0.28, pass: false },
        hangingMeat:         { value: 0.34, pass: true  },
        foreignMatter:       { value: 0.09, pass: false },
        fungusParasites:     { value: 0.26, pass: true  },
        presenceOfMetal:     { value: 1.45, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7', sampleNumber: '42214', section: 'Beheading', batchInfo: '136-13c-12/14-3215',
        batchNumber: '781-22-9876', count: '21h', quantity: '67890', sampleSize: '11 gms',
        uniformity: '44', totalDefects: '11 gms -88%', finalResult: 'Pass', correctiveAction: 'Premium batch',
        decomposition:       { value: 0.49, pass: true  },
        discoloration:       { value: 0.10, pass: false },
        softShell:           { value: 0.34, pass: true  },
        looseShell:          { value: 0.34, pass: true  },
        blackTail:           { value: 0.34, pass: true  },
        blackSpots:          { value: 0.34, pass: true  },
        passFailSpec:        { value: 0.33, pass: true  },
        correctiveActionSpec: null,
        brokenDamaged:       { value: 0.26, pass: true  },
        hangingMeat:         null,
        foreignMatter:       { value: 0.34, pass: true  },
        fungusParasites:     { value: 4.62, pass: true  },
        presenceOfMetal:     { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
    ],
    'others': [
      {
        key: '1', sampleNumber: '42215', section: 'Beheading', batchInfo: '150-13c-12/14-3216',
        batchNumber: '125-67-3216', count: '12c', quantity: '61234', sampleSize: '13 gms',
        uniformity: '41', totalDefects: '13 gms -97%', finalResult: 'Pass', correctiveAction: 'Within spec limits',
        decomposition:       { value: 0.45, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShell:           { value: 0.34, pass: true  },
        looseShell:          { value: 0.34, pass: true  },
        blackTail:           { value: 0.34, pass: true  },
        blackSpots:          { value: 0.22, pass: false },
        passFailSpec:        { value: 0.33, pass: true  },
        correctiveActionSpec: null,
        brokenDamaged:       { value: 0.26, pass: true  },
        hangingMeat:         null,
        foreignMatter:       { value: 0.34, pass: true  },
        fungusParasites:     { value: 0.26, pass: true  },
        presenceOfMetal:     { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', sampleNumber: '42215', section: 'Beheading', batchInfo: '150-13c-12/14-3216',
        batchNumber: '237-78-4322', count: '14b', quantity: '24567', sampleSize: '9 gms',
        uniformity: '29', totalDefects: '9 gms -76%', finalResult: 'Fail', correctiveAction: 'Fungus detected',
        decomposition:       { value: 0.09, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        softShell:           { value: 0.22, pass: false },
        looseShell:          { value: 0.26, pass: true  },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.10, pass: false },
        passFailSpec:        { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:       { value: 0.28, pass: false },
        hangingMeat:         null,
        foreignMatter:       { value: 0.26, pass: true  },
        fungusParasites:     { value: 0.08, pass: false },
        presenceOfMetal:     { value: 1.45, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3', sampleNumber: '42215', section: 'Beheading', batchInfo: '150-13c-12/14-3216',
        batchNumber: '348-89-5433', count: '10d', quantity: '79012', sampleSize: '17 gms',
        uniformity: '47', totalDefects: '17 gms -91%', finalResult: 'Pass', correctiveAction: 'Good quality',
        decomposition:       { value: 0.49, pass: true  },
        discoloration:       { value: 0.10, pass: false },
        softShell:           { value: 0.34, pass: true  },
        looseShell:          { value: 0.34, pass: true  },
        blackTail:           { value: 0.34, pass: true  },
        blackSpots:          { value: 0.34, pass: true  },
        passFailSpec:        { value: 0.33, pass: true  },
        correctiveActionSpec: null,
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeat:         { value: 0.26, pass: true  },
        foreignMatter:       { value: 0.34, pass: true  },
        fungusParasites:     { value: 4.62, pass: true  },
        presenceOfMetal:     { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4', sampleNumber: '42215', section: 'Beheading', batchInfo: '150-13c-12/14-3216',
        batchNumber: '459-90-6544', count: '16e', quantity: '35678', sampleSize: '23 gms',
        uniformity: '21', totalDefects: '23 gms -66%', finalResult: 'Fail', correctiveAction: 'Loose shell found',
        decomposition:       { value: 0.22, pass: false },
        discoloration:       { value: 0.10, pass: false },
        softShell:           { value: 0.08, pass: false },
        looseShell:          { value: 0.34, pass: true  },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.10, pass: false },
        passFailSpec:        { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:       { value: 0.28, pass: false },
        hangingMeat:         null,
        foreignMatter:       { value: 0.26, pass: true  },
        fungusParasites:     { value: 0.22, pass: false },
        presenceOfMetal:     { value: 1.45, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5', sampleNumber: '42215', section: 'Beheading', batchInfo: '150-13c-12/14-3216',
        batchNumber: '570-01-7655', count: '18f', quantity: '46789', sampleSize: '28 gms',
        uniformity: '17', totalDefects: '28 gms -55%', finalResult: 'Pass', correctiveAction: 'Minimal defects',
        decomposition:       { value: 0.26, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShell:           { value: 0.34, pass: true  },
        looseShell:          { value: 0.22, pass: false },
        blackTail:           { value: 0.34, pass: true  },
        blackSpots:          { value: 0.34, pass: true  },
        passFailSpec:        { value: 0.33, pass: true  },
        correctiveActionSpec: null,
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeat:         null,
        foreignMatter:       { value: 0.34, pass: true  },
        fungusParasites:     { value: 4.62, pass: true  },
        presenceOfMetal:     { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6', sampleNumber: '42215', section: 'Beheading', batchInfo: '150-13c-12/14-3216',
        batchNumber: '681-12-8766', count: '20g', quantity: '57890', sampleSize: '20 gms',
        uniformity: '32', totalDefects: '20 gms -70%', finalResult: 'Fail', correctiveAction: 'Metal traces found',
        decomposition:       { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        softShell:           { value: 0.22, pass: false },
        looseShell:          { value: 0.26, pass: true  },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.10, pass: false },
        passFailSpec:        { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:       { value: 0.28, pass: false },
        hangingMeat:         { value: 0.34, pass: true  },
        foreignMatter:       { value: 0.26, pass: true  },
        fungusParasites:     { value: 0.22, pass: false },
        presenceOfMetal:     { value: 1.45, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7', sampleNumber: '42215', section: 'Beheading', batchInfo: '150-13c-12/14-3216',
        batchNumber: '792-23-9877', count: '22h', quantity: '68901', sampleSize: '12 gms',
        uniformity: '43', totalDefects: '12 gms -87%', finalResult: 'Pass', correctiveAction: 'Premium batch',
        decomposition:       { value: 0.49, pass: true  },
        discoloration:       { value: 0.10, pass: false },
        softShell:           { value: 0.34, pass: true  },
        looseShell:          { value: 0.34, pass: true  },
        blackTail:           { value: 0.34, pass: true  },
        blackSpots:          { value: 0.34, pass: true  },
        passFailSpec:        { value: 0.33, pass: true  },
        correctiveActionSpec: null,
        brokenDamaged:       { value: 0.26, pass: true  },
        hangingMeat:         null,
        foreignMatter:       { value: 0.34, pass: true  },
        fungusParasites:     { value: 4.62, pass: true  },
        presenceOfMetal:     { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
    ],
  },
};

export default BeheadingConfig;
