const BreadingConfig = {
  baseCols: [
    { key: 'sampleNumber',     label: 'Sample Number'        },
    { key: 'section',          label: 'Section'              },
    { key: 'batchInfo',        label: 'Batch Info'           },
    { key: 'batchNumber',      label: 'Batch Number'         },
    { key: 'brand',            label: 'Brand'                },
    { key: 'grade',            label: 'Grade'                },
    { key: 'count',            label: 'Count'                },
    { key: 'variety',          label: 'Variety'              },
    { key: 'sampleSize',       label: 'Sample Size'          },
    { key: 'uniformity',       label: 'Uniformity'           },
    { key: 'photo',            label: 'Photo', type: 'photo' },
    { key: 'totalDefects',     label: 'Total Defects (gms)'  },
    { key: 'finalResult',      label: 'Final Result', type: 'passFail' },
    { key: 'correctiveAction', label: 'Corrective Action'    },
  ],
  extraCols: [],
  valueCols: [
    { key: 'breadingCoating', label: 'Breading Coating (%)' },
    { key: 'holidays',        label: 'Holidays'             },
    { key: 'haloes',          label: 'Haloes'               },
    { key: 'bailingUp',       label: 'Bailing Up'           },
    { key: 'damaged',         label: 'Damaged'              },
    { key: 'passFailSpec',    label: 'Pass/Fail (Spec)'     },
    { key: 'correctiveActionSpec', label: 'Corrective Action' },
    { key: 'breadedCount',    label: 'Breaded Count'        },
    { key: 'overCount',       label: 'Over Count'           },
    { key: 'blackTail',       label: 'Black Tail'           },
    { key: 'blackSpots',      label: 'Black Spots'          },
  ],
  actionLabel: 'Action',
  data: {
    'pre-harvest': [
      {
        key: '1', sampleNumber: '42213', section: 'Breading',
        batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-3214',
        brand: 'Walmart', grade: '12/14', count: '12c', variety: 'EZPL',
        sampleSize: '12 gms', uniformity: '1:2', totalDefects: '12 gms -100%',
        finalResult: 'Pass', correctiveAction: 'Shrimp has Dark Spots',
        breadingCoating:      { value: 0.49, pass: true  },
        holidays:             { value: 0.10, pass: false },
        haloes:               { value: 0.34, pass: true  },
        bailingUp:            { value: 0.34, pass: true  },
        damaged:              { value: 0.34, pass: true  },
        passFailSpec:         { value: 0.10, pass: false },
        correctiveActionSpec: { value: 0.34, pass: true  },
        breadedCount:         { value: 0.28, pass: false },
        overCount:            { value: 0.34, pass: true  },
        blackTail:            { value: 0.34, pass: true  },
        blackSpots:           { value: 0.33, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', sampleNumber: '42213', section: 'Breading',
        batchInfo: '125-13c-12/14-3214', batchNumber: '223-45-6789',
        brand: 'Target', grade: '11/21', count: '16c', variety: 'BTTLE',
        sampleSize: '8 gms', uniformity: '1:1', totalDefects: '8 gms -80%',
        finalResult: 'Pass', correctiveAction: 'Butter has Solidified',
        breadingCoating:      { value: 0.26, pass: true  },
        holidays:             { value: 0.22, pass: false },
        haloes:               { value: 0.26, pass: true  },
        bailingUp:            { value: 0.22, pass: false },
        damaged:              { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        breadedCount:         { value: 0.22, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '3', sampleNumber: '42213', section: 'Breading',
        batchInfo: '125-13c-12/14-3214', batchNumber: '334-56-7890',
        brand: 'Costco', grade: '01/23', count: '20c', variety: 'CHZ',
        sampleSize: '15 gms', uniformity: '1:3', totalDefects: '15 gms -90%',
        finalResult: 'Fail', correctiveAction: 'Cheese is Moldy',
        breadingCoating:      { value: 0.22, pass: false },
        holidays:             { value: 0.26, pass: true  },
        haloes:               { value: 0.22, pass: false },
        bailingUp:            { value: 0.26, pass: true  },
        damaged:              { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        breadedCount:         { value: 0.35, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '4', sampleNumber: '42213', section: 'Breading',
        batchInfo: '125-13c-12/14-3214', batchNumber: '445-67-8901',
        brand: 'Kroger', grade: '05/22', count: '20c', variety: 'MLK',
        sampleSize: '1 L', uniformity: '2:1', totalDefects: '1 L -95%',
        finalResult: 'Pass', correctiveAction: 'Milk is Expired',
        breadingCoating:      { value: 0.26, pass: true  },
        holidays:             { value: 0.22, pass: false },
        haloes:               { value: 0.26, pass: true  },
        bailingUp:            { value: 0.22, pass: false },
        damaged:              { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        breadedCount:         { value: 0.22, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '5', sampleNumber: '42213', section: 'Breading',
        batchInfo: '125-13c-12/14-3214', batchNumber: '556-78-9012',
        brand: 'Aldi', grade: '03/24', count: '20c', variety: 'EGGS',
        sampleSize: '12 pcs', uniformity: '3:1', totalDefects: '12 pcs -100%',
        finalResult: 'Pass', correctiveAction: 'Eggs are Fresh',
        breadingCoating:      { value: 0.22, pass: false },
        holidays:             { value: 0.26, pass: true  },
        haloes:               { value: 0.22, pass: false },
        bailingUp:            { value: 0.26, pass: true  },
        damaged:              { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        breadedCount:         { value: 0.26, pass: true  },
        overCount:            { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6', sampleNumber: '42213', section: 'Breading',
        batchInfo: '125-13c-12/14-3214', batchNumber: '667-89-0123',
        brand: 'Whole Foods', grade: '07/25', count: '20c', variety: 'TMT',
        sampleSize: '500 gms', uniformity: '1:1', totalDefects: '500 gms -85%',
        finalResult: 'Pass', correctiveAction: 'Tomatoes are Fresh',
        breadingCoating:      { value: 0.26, pass: true  },
        holidays:             { value: 0.22, pass: false },
        haloes:               { value: 0.26, pass: true  },
        bailingUp:            { value: 0.22, pass: false },
        damaged:              { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        breadedCount:         { value: 0.22, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '7', sampleNumber: '42213', section: 'Breading',
        batchInfo: '125-13c-12/14-3214', batchNumber: '778-90-1234',
        brand: "Trader Joe's", grade: '09/26', count: '18c', variety: 'SPCE',
        sampleSize: '250 gms', uniformity: '1:2', totalDefects: '250 gms -90%',
        finalResult: 'Fail', correctiveAction: 'Spice mix expired',
        breadingCoating:      { value: 0.22, pass: false },
        holidays:             { value: 0.26, pass: true  },
        haloes:               { value: 0.22, pass: false },
        bailingUp:            { value: 0.26, pass: true  },
        damaged:              { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        breadedCount:         { value: 0.38, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
    ],
    'processing': [
      {
        key: '1', sampleNumber: '42301', section: 'Breading',
        batchInfo: '136-14c-10/12-1122', batchNumber: '136-70-1122',
        brand: 'Costco', grade: '10/12', count: '14c', variety: 'EZPL',
        sampleSize: '12 gms', uniformity: '1:2', totalDefects: '12 gms -95%',
        finalResult: 'Pass', correctiveAction: 'Consistent batch',
        breadingCoating:      { value: 0.46, pass: true  },
        holidays:             { value: 0.22, pass: false },
        haloes:               { value: 0.26, pass: true  },
        bailingUp:            { value: 0.22, pass: false },
        damaged:              { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        breadedCount:         { value: 0.22, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', sampleNumber: '42301', section: 'Breading',
        batchInfo: '136-14c-10/12-1122', batchNumber: '137-60-2233',
        brand: 'Walmart', grade: '11/13', count: '16c', variety: 'BTTLE',
        sampleSize: '8 gms', uniformity: '1:1', totalDefects: '8 gms -80%',
        finalResult: 'Fail', correctiveAction: 'Batter too thick',
        breadingCoating:      { value: 0.22, pass: false },
        holidays:             { value: 0.26, pass: true  },
        haloes:               { value: 0.22, pass: false },
        bailingUp:            { value: 0.09, pass: false },
        damaged:              { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        breadedCount:         { value: 0.32, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3', sampleNumber: '42301', section: 'Breading',
        batchInfo: '136-14c-10/12-1122', batchNumber: '138-50-3344',
        brand: 'Target', grade: '01/24', count: '20c', variety: 'CHZ',
        sampleSize: '15 gms', uniformity: '1:3', totalDefects: '15 gms -100%',
        finalResult: 'Pass', correctiveAction: 'Good coating',
        breadingCoating:      { value: 0.48, pass: true  },
        holidays:             { value: 0.22, pass: false },
        haloes:               { value: 0.26, pass: true  },
        bailingUp:            { value: 0.22, pass: false },
        damaged:              { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        breadedCount:         { value: 0.22, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4', sampleNumber: '42301', section: 'Breading',
        batchInfo: '136-14c-10/12-1122', batchNumber: '139-40-4455',
        brand: 'Kroger', grade: '05/23', count: '20c', variety: 'MLK',
        sampleSize: '1 L', uniformity: '2:1', totalDefects: '1 L -90%',
        finalResult: 'Fail', correctiveAction: 'Milk curdled',
        breadingCoating:      { value: 0.22, pass: false },
        holidays:             { value: 0.26, pass: true  },
        haloes:               { value: 0.22, pass: false },
        bailingUp:            { value: 0.26, pass: true  },
        damaged:              { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        breadedCount:         { value: 0.34, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5', sampleNumber: '42301', section: 'Breading',
        batchInfo: '136-14c-10/12-1122', batchNumber: '140-30-5566',
        brand: 'Aldi', grade: '03/25', count: '20c', variety: 'EGGS',
        sampleSize: '12 pcs', uniformity: '3:1', totalDefects: '12 pcs -95%',
        finalResult: 'Pass', correctiveAction: 'Eggs within spec',
        breadingCoating:      { value: 0.43, pass: true  },
        holidays:             { value: 0.22, pass: false },
        haloes:               { value: 0.26, pass: true  },
        bailingUp:            { value: 0.22, pass: false },
        damaged:              { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        breadedCount:         { value: 0.22, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6', sampleNumber: '42301', section: 'Breading',
        batchInfo: '136-14c-10/12-1122', batchNumber: '141-20-6677',
        brand: 'Whole Foods', grade: '07/26', count: '20c', variety: 'TMT',
        sampleSize: '500 gms', uniformity: '1:1', totalDefects: '500 gms -80%',
        finalResult: 'Fail', correctiveAction: 'Tomatoes overripe',
        breadingCoating:      { value: 0.22, pass: false },
        holidays:             { value: 0.26, pass: true  },
        haloes:               { value: 0.22, pass: false },
        bailingUp:            { value: 0.26, pass: true  },
        damaged:              { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        breadedCount:         { value: 0.22, pass: false },
        overCount:            { value: 0.08, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7', sampleNumber: '42301', section: 'Breading',
        batchInfo: '136-14c-10/12-1122', batchNumber: '142-10-7788',
        brand: "Trader Joe's", grade: '09/27', count: '18c', variety: 'SPCE',
        sampleSize: '250 gms', uniformity: '1:2', totalDefects: '250 gms -100%',
        finalResult: 'Pass', correctiveAction: 'Premium coating',
        breadingCoating:      { value: 0.50, pass: true  },
        holidays:             { value: 0.22, pass: false },
        haloes:               { value: 0.26, pass: true  },
        bailingUp:            { value: 0.22, pass: false },
        damaged:              { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        breadedCount:         { value: 0.22, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
    ],
    'others': [
      {
        key: '1', sampleNumber: '42401', section: 'Breading',
        batchInfo: '150-12c-08/10-2211', batchNumber: '150-80-2211',
        brand: 'Costco', grade: '10/12', count: '14c', variety: 'EZPL',
        sampleSize: '12 gms', uniformity: '1:2', totalDefects: '12 gms -100%',
        finalResult: 'Pass', correctiveAction: 'Within spec limits',
        breadingCoating:      { value: 0.45, pass: true  },
        holidays:             { value: 0.22, pass: false },
        haloes:               { value: 0.26, pass: true  },
        bailingUp:            { value: 0.22, pass: false },
        damaged:              { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        breadedCount:         { value: 0.22, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', sampleNumber: '42401', section: 'Breading',
        batchInfo: '150-12c-08/10-2211', batchNumber: '151-70-3322',
        brand: 'Walmart', grade: '11/22', count: '16c', variety: 'BTTLE',
        sampleSize: '8 gms', uniformity: '1:1', totalDefects: '8 gms -85%',
        finalResult: 'Fail', correctiveAction: 'Coating uneven',
        breadingCoating:      { value: 0.22, pass: false },
        holidays:             { value: 0.26, pass: true  },
        haloes:               { value: 0.22, pass: false },
        bailingUp:            { value: 0.26, pass: true  },
        damaged:              { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        breadedCount:         { value: 0.37, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3', sampleNumber: '42401', section: 'Breading',
        batchInfo: '150-12c-08/10-2211', batchNumber: '152-60-4433',
        brand: 'Target', grade: '01/24', count: '20c', variety: 'CHZ',
        sampleSize: '15 gms', uniformity: '1:3', totalDefects: '15 gms -90%',
        finalResult: 'Pass', correctiveAction: 'Cheese blend correct',
        breadingCoating:      { value: 0.47, pass: true  },
        holidays:             { value: 0.22, pass: false },
        haloes:               { value: 0.26, pass: true  },
        bailingUp:            { value: 0.22, pass: false },
        damaged:              { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        breadedCount:         { value: 0.22, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4', sampleNumber: '42401', section: 'Breading',
        batchInfo: '150-12c-08/10-2211', batchNumber: '153-50-5544',
        brand: 'Kroger', grade: '05/23', count: '20c', variety: 'MLK',
        sampleSize: '1 L', uniformity: '2:1', totalDefects: '1 L -95%',
        finalResult: 'Fail', correctiveAction: 'Milk past expiry',
        breadingCoating:      { value: 0.22, pass: false },
        holidays:             { value: 0.09, pass: false },
        haloes:               { value: 0.26, pass: true  },
        bailingUp:            { value: 0.22, pass: false },
        damaged:              { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        breadedCount:         { value: 0.33, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5', sampleNumber: '42401', section: 'Breading',
        batchInfo: '150-12c-08/10-2211', batchNumber: '154-40-6655',
        brand: 'Aldi', grade: '03/25', count: '20c', variety: 'EGGS',
        sampleSize: '12 pcs', uniformity: '3:1', totalDefects: '12 pcs -100%',
        finalResult: 'Pass', correctiveAction: 'Minimal defects',
        breadingCoating:      { value: 0.41, pass: true  },
        holidays:             { value: 0.22, pass: false },
        haloes:               { value: 0.26, pass: true  },
        bailingUp:            { value: 0.22, pass: false },
        damaged:              { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        breadedCount:         { value: 0.22, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6', sampleNumber: '42401', section: 'Breading',
        batchInfo: '150-12c-08/10-2211', batchNumber: '155-30-7766',
        brand: 'Whole Foods', grade: '07/26', count: '20c', variety: 'TMT',
        sampleSize: '500 gms', uniformity: '1:1', totalDefects: '500 gms -80%',
        finalResult: 'Fail', correctiveAction: 'Tomatoes bruised',
        breadingCoating:      { value: 0.22, pass: false },
        holidays:             { value: 0.26, pass: true  },
        haloes:               { value: 0.22, pass: false },
        bailingUp:            { value: 0.26, pass: true  },
        damaged:              { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        breadedCount:         { value: 0.22, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.08, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7', sampleNumber: '42401', section: 'Breading',
        batchInfo: '150-12c-08/10-2211', batchNumber: '156-20-8877',
        brand: "Trader Joe's", grade: '09/27', count: '18c', variety: 'SPCE',
        sampleSize: '250 gms', uniformity: '1:2', totalDefects: '250 gms -95%',
        finalResult: 'Pass', correctiveAction: 'Premium quality',
        breadingCoating:      { value: 0.52, pass: true  },
        holidays:             { value: 0.22, pass: false },
        haloes:               { value: 0.26, pass: true  },
        bailingUp:            { value: 0.22, pass: false },
        damaged:              { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        breadedCount:         { value: 0.22, pass: false },
        overCount:            { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
    ],
  },
};

export default BreadingConfig;
