const CookingPeelingCuttingConfig = {
  baseCols: [
    { key: 'sampleNumber',     label: 'Sample Number'        },
    { key: 'section',          label: 'Section'              },
    { key: 'batchInfo',        label: 'Batch Info'           },
    { key: 'batchNumber',      label: 'Batch Number'         },
    { key: 'brand',            label: 'Brand'                },
    { key: 'grade',            label: 'Grade'                },
    { key: 'count',            label: 'Count'                },
    { key: 'variety',          label: 'Variety'              },
    { key: 'sampleSize',       label: 'Sample Size'          },
    { key: 'uniformity',       label: 'Uniformity'           },
    { key: 'photo',            label: 'Photo', type: 'photo' },
    { key: 'totalDefects',     label: 'Total Defects (gms)'  },
    { key: 'finalResult',      label: 'Final Result', type: 'passFail' },
    { key: 'correctiveAction', label: 'Corrective Action'    },
  ],
  extraCols: [],
  valueCols: [
    { key: 'decomposition',       label: 'Decomposition (Spec)'          },
    { key: 'discoloration',       label: 'Discoloration (Spec)'          },
    { key: 'softShellLooseShell', label: 'Soft Shell/Loose Shell (Spec)' },
    { key: 'sandVein',            label: 'Sand Vein (Spec)'              },
    { key: 'broken',              label: 'Broken (Spec)'                 },
    { key: 'damaged',             label: 'Damaged (Spec)'                },
    { key: 'blackTail',           label: 'Black Tail (Spec)'             },
    { key: 'blackSpots',          label: 'Black Spots (Spec)'            },
    { key: 'legsShellSwimmerets', label: 'Legs/Shell/Swimmerets'         },
    { key: 'passFailSpec',        label: 'Pass/Fail (Spec)'              },
    { key: 'correctiveActionSpec',label: 'Corrective Action (Spec)'      },
    { key: 'brokenDamaged',       label: 'Broken/Damaged'                },
    { key: 'hangingMeatNeckMeat', label: 'Hanging Meat/Neck Meat (Spec)' },
    { key: 'wrongCut',            label: 'Wrong Cut'                     },
    { key: 'uncutSpec',           label: 'Uncut (Spec)'                  },
    { key: 'brokenTailSpec',      label: 'Broken Tail (Spec)'            },
    { key: 'chippedTailSpec',     label: 'Chipped Tail (Spec)'           },
    { key: 'muddySmellSpec',      label: 'Muddy Smell (Spec)'            },
    { key: 'parasitesSpec',       label: 'Parasites (Spec)'              },
    { key: 'foreignMatterSpec',   label: 'Foreign Matter (Spec)'         },
    { key: 'presenceOfMetal',     label: 'Presence of Metal'             },
  ],
  actionLabel: 'Action',
  data: {
    'pre-harvest': [
      {
        key: '1', sampleNumber: '42213', section: 'Cooking Peeling & Cutting',
        batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-3214',
        brand: 'Walmart', grade: '12/14', count: '12c', variety: 'EZPL',
        sampleSize: '12 gms', uniformity: '1:2', totalDefects: '12 gms -100%',
        finalResult: 'Pass', correctiveAction: 'Shrimp has Dark Spots',
        decomposition:       { value: 0.49, pass: true  },
        discoloration:       { value: 0.10, pass: false },
        softShellLooseShell: { value: 0.34, pass: true  },
        sandVein:            { value: 0.34, pass: true  },
        broken:              { value: 0.34, pass: true  },
        damaged:             { value: 0.10, pass: false },
        blackTail:           { value: 0.34, pass: true  },
        blackSpots:          { value: 0.10, pass: false },
        legsShellSwimmerets: { value: 0.10, pass: false },
        passFailSpec:        { value: 0.33, pass: true  },
        correctiveActionSpec:{ value: 0.34, pass: true  },
        brokenDamaged:       { value: 0.28, pass: false },
        hangingMeatNeckMeat: { value: 0.34, pass: true  },
        wrongCut:            { value: 0.34, pass: true  },
        uncutSpec:           { value: 0.28, pass: false },
        brokenTailSpec:      { value: 0.33, pass: true  },
        chippedTailSpec:     { value: 0.33, pass: true  },
        muddySmellSpec:      { value: 0.34, pass: true  },
        parasitesSpec:       { value: 0.34, pass: true  },
        foreignMatterSpec:   { value: 0.34, pass: true  },
        presenceOfMetal:     { value: 1.45, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', sampleNumber: '42213', section: 'Cooking Peeling & Cutting',
        batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-4321',
        brand: 'Target', grade: '12/15', count: '10c', variety: 'GRL',
        sampleSize: '8 gms', uniformity: '1:1', totalDefects: '8 gms -90%',
        finalResult: 'Pass', correctiveAction: 'Seasoning is Cloudy',
        decomposition:       { value: 0.26, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShellLooseShell: { value: 0.26, pass: true  },
        sandVein:            { value: 0.22, pass: false },
        broken:              { value: 0.26, pass: true  },
        damaged:             { value: 0.22, pass: false },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.22, pass: false },
        legsShellSwimmerets: { value: 0.26, pass: true  },
        passFailSpec:        { value: 0.22, pass: false },
        correctiveActionSpec:{ value: 0.26, pass: true  },
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '3', sampleNumber: '42213', section: 'Cooking Peeling & Cutting',
        batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-5432',
        brand: 'Costco', grade: '12/16', count: '2kg', variety: 'BAK',
        sampleSize: '1 kg', uniformity: '1:3', totalDefects: '1 kg -95%',
        finalResult: 'Pass', correctiveAction: 'Flour is Expired',
        decomposition:       { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        softShellLooseShell: { value: 0.22, pass: false },
        sandVein:            { value: 0.26, pass: true  },
        broken:              { value: 0.22, pass: false },
        damaged:             { value: 0.26, pass: true  },
        blackTail:           { value: 0.22, pass: false },
        blackSpots:          { value: 0.26, pass: true  },
        legsShellSwimmerets: { value: 0.22, pass: false },
        passFailSpec:        { value: 0.26, pass: true  },
        correctiveActionSpec:{ value: 0.22, pass: false },
        brokenDamaged:       { value: 0.35, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4', sampleNumber: '42213', section: 'Cooking Peeling & Cutting',
        batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-6543',
        brand: 'IKEA', grade: '12/17', count: '1pc', variety: 'CHB',
        sampleSize: '500 gms', uniformity: '1:1', totalDefects: '500 gms -100%',
        finalResult: 'Pass', correctiveAction: 'Board is Cracked',
        decomposition:       { value: 0.26, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShellLooseShell: { value: 0.26, pass: true  },
        sandVein:            { value: 0.22, pass: false },
        broken:              { value: 0.26, pass: true  },
        damaged:             { value: 0.22, pass: false },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.22, pass: false },
        legsShellSwimmerets: { value: 0.26, pass: true  },
        passFailSpec:        { value: 0.22, pass: false },
        correctiveActionSpec:{ value: 0.26, pass: true  },
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '5', sampleNumber: '42213', section: 'Cooking Peeling & Cutting',
        batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-7654',
        brand: 'Home Depot', grade: '12/18', count: '1pc', variety: 'FRY',
        sampleSize: '1 kg', uniformity: '2:1', totalDefects: '1 kg -80%',
        finalResult: 'Fail', correctiveAction: 'Pan has Scratches',
        decomposition:       { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        softShellLooseShell: { value: 0.22, pass: false },
        sandVein:            { value: 0.26, pass: true  },
        broken:              { value: 0.22, pass: false },
        damaged:             { value: 0.26, pass: true  },
        blackTail:           { value: 0.22, pass: false },
        blackSpots:          { value: 0.26, pass: true  },
        legsShellSwimmerets: { value: 0.22, pass: false },
        passFailSpec:        { value: 0.26, pass: true  },
        correctiveActionSpec:{ value: 0.22, pass: false },
        brokenDamaged:       { value: 0.30, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.33, pass: false },
        brokenTailSpec:      { value: 0.26, pass: true  },
        chippedTailSpec:     { value: 0.22, pass: false },
        muddySmellSpec:      { value: 0.26, pass: true  },
        parasitesSpec:       { value: 0.22, pass: false },
        foreignMatterSpec:   { value: 0.26, pass: true  },
        presenceOfMetal:     { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '6', sampleNumber: '42213', section: 'Cooking Peeling & Cutting',
        batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-8765',
        brand: 'Safeway', grade: '12/19', count: '3pc', variety: 'STM',
        sampleSize: '500 gms', uniformity: '1:2', totalDefects: '500 gms -90%',
        finalResult: 'Pass', correctiveAction: 'Steamer needs cleaning',
        decomposition:       { value: 0.26, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShellLooseShell: { value: 0.26, pass: true  },
        sandVein:            { value: 0.22, pass: false },
        broken:              { value: 0.26, pass: true  },
        damaged:             { value: 0.22, pass: false },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.22, pass: false },
        legsShellSwimmerets: { value: 0.26, pass: true  },
        passFailSpec:        { value: 0.22, pass: false },
        correctiveActionSpec:{ value: 0.26, pass: true  },
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '7', sampleNumber: '42213', section: 'Cooking Peeling & Cutting',
        batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-9876',
        brand: "Trader Joe's", grade: '12/20', count: '2pc', variety: 'GRL',
        sampleSize: '1 kg', uniformity: '1:1', totalDefects: '1 kg -100%',
        finalResult: 'Fail', correctiveAction: 'Grilling oil expired',
        decomposition:       { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        softShellLooseShell: { value: 0.22, pass: false },
        sandVein:            { value: 0.26, pass: true  },
        broken:              { value: 0.22, pass: false },
        damaged:             { value: 0.26, pass: true  },
        blackTail:           { value: 0.22, pass: false },
        blackSpots:          { value: 0.26, pass: true  },
        legsShellSwimmerets: { value: 0.22, pass: false },
        passFailSpec:        { value: 0.26, pass: true  },
        correctiveActionSpec:{ value: 0.22, pass: false },
        brokenDamaged:       { value: 0.38, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 1.12, pass: false },
        status: 'Fail', action: 'Rejected',
      },
    ],
    'processing': [
      {
        key: '1', sampleNumber: '42301', section: 'Cooking Peeling & Cutting',
        batchInfo: '136-14c-10/12-1122', batchNumber: '136-70-1122',
        brand: 'Costco', grade: '10/12', count: '14b', variety: 'EZPL',
        sampleSize: '14 gms', uniformity: '2:1', totalDefects: '14 gms -95%',
        finalResult: 'Pass', correctiveAction: 'Consistent batch',
        decomposition:       { value: 0.46, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShellLooseShell: { value: 0.26, pass: true  },
        sandVein:            { value: 0.22, pass: false },
        broken:              { value: 0.26, pass: true  },
        damaged:             { value: 0.22, pass: false },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.22, pass: false },
        legsShellSwimmerets: { value: 0.26, pass: true  },
        passFailSpec:        { value: 0.22, pass: false },
        correctiveActionSpec:{ value: 0.26, pass: true  },
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', sampleNumber: '42301', section: 'Cooking Peeling & Cutting',
        batchInfo: '136-14c-10/12-1122', batchNumber: '137-60-2233',
        brand: 'Walmart', grade: '10/13', count: '12c', variety: 'GRL',
        sampleSize: '12 gms', uniformity: '1:2', totalDefects: '12 gms -90%',
        finalResult: 'Fail', correctiveAction: 'Grill marks uneven',
        decomposition:       { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        softShellLooseShell: { value: 0.22, pass: false },
        sandVein:            { value: 0.26, pass: true  },
        broken:              { value: 0.22, pass: false },
        damaged:             { value: 0.09, pass: false },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.22, pass: false },
        legsShellSwimmerets: { value: 0.26, pass: true  },
        passFailSpec:        { value: 0.22, pass: false },
        correctiveActionSpec:{ value: 0.26, pass: true  },
        brokenDamaged:       { value: 0.32, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3', sampleNumber: '42301', section: 'Cooking Peeling & Cutting',
        batchInfo: '136-14c-10/12-1122', batchNumber: '138-50-3344',
        brand: 'Target', grade: '10/14', count: '16a', variety: 'BAK',
        sampleSize: '1 kg', uniformity: '1:3', totalDefects: '1 kg -100%',
        finalResult: 'Pass', correctiveAction: 'Good uniformity',
        decomposition:       { value: 0.48, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShellLooseShell: { value: 0.26, pass: true  },
        sandVein:            { value: 0.22, pass: false },
        broken:              { value: 0.26, pass: true  },
        damaged:             { value: 0.22, pass: false },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.22, pass: false },
        legsShellSwimmerets: { value: 0.26, pass: true  },
        passFailSpec:        { value: 0.22, pass: false },
        correctiveActionSpec:{ value: 0.26, pass: true  },
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4', sampleNumber: '42301', section: 'Cooking Peeling & Cutting',
        batchInfo: '136-14c-10/12-1122', batchNumber: '139-40-4455',
        brand: 'Kroger', grade: '10/15', count: '1pc', variety: 'FRY',
        sampleSize: '500 gms', uniformity: '1:1', totalDefects: '500 gms -95%',
        finalResult: 'Fail', correctiveAction: 'Frying oil degraded',
        decomposition:       { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        softShellLooseShell: { value: 0.22, pass: false },
        sandVein:            { value: 0.26, pass: true  },
        broken:              { value: 0.22, pass: false },
        damaged:             { value: 0.26, pass: true  },
        blackTail:           { value: 0.22, pass: false },
        blackSpots:          { value: 0.26, pass: true  },
        legsShellSwimmerets: { value: 0.22, pass: false },
        passFailSpec:        { value: 0.26, pass: true  },
        correctiveActionSpec:{ value: 0.22, pass: false },
        brokenDamaged:       { value: 0.34, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 1.20, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5', sampleNumber: '42301', section: 'Cooking Peeling & Cutting',
        batchInfo: '136-14c-10/12-1122', batchNumber: '140-30-5566',
        brand: 'Whole Foods', grade: '10/16', count: '2pc', variety: 'STM',
        sampleSize: '1 kg', uniformity: '2:1', totalDefects: '1 kg -100%',
        finalResult: 'Pass', correctiveAction: 'Steam pressure normal',
        decomposition:       { value: 0.43, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShellLooseShell: { value: 0.26, pass: true  },
        sandVein:            { value: 0.22, pass: false },
        broken:              { value: 0.26, pass: true  },
        damaged:             { value: 0.22, pass: false },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.22, pass: false },
        legsShellSwimmerets: { value: 0.26, pass: true  },
        passFailSpec:        { value: 0.22, pass: false },
        correctiveActionSpec:{ value: 0.26, pass: true  },
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6', sampleNumber: '42301', section: 'Cooking Peeling & Cutting',
        batchInfo: '136-14c-10/12-1122', batchNumber: '141-20-6677',
        brand: "Sam's Club", grade: '10/17', count: '3pc', variety: 'CHB',
        sampleSize: '500 gms', uniformity: '1:2', totalDefects: '500 gms -90%',
        finalResult: 'Fail', correctiveAction: 'Char marks excessive',
        decomposition:       { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        softShellLooseShell: { value: 0.22, pass: false },
        sandVein:            { value: 0.26, pass: true  },
        broken:              { value: 0.22, pass: false },
        damaged:             { value: 0.26, pass: true  },
        blackTail:           { value: 0.22, pass: false },
        blackSpots:          { value: 0.09, pass: false },
        legsShellSwimmerets: { value: 0.26, pass: true  },
        passFailSpec:        { value: 0.22, pass: false },
        correctiveActionSpec:{ value: 0.26, pass: true  },
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7', sampleNumber: '42301', section: 'Cooking Peeling & Cutting',
        batchInfo: '136-14c-10/12-1122', batchNumber: '142-10-7788',
        brand: "Trader Joe's", grade: '10/18', count: '1pc', variety: 'EZPL',
        sampleSize: '12 gms', uniformity: '1:1', totalDefects: '12 gms -100%',
        finalResult: 'Pass', correctiveAction: 'Premium batch',
        decomposition:       { value: 0.50, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShellLooseShell: { value: 0.26, pass: true  },
        sandVein:            { value: 0.22, pass: false },
        broken:              { value: 0.26, pass: true  },
        damaged:             { value: 0.22, pass: false },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.22, pass: false },
        legsShellSwimmerets: { value: 0.26, pass: true  },
        passFailSpec:        { value: 0.22, pass: false },
        correctiveActionSpec:{ value: 0.26, pass: true  },
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
    ],
    'others': [
      {
        key: '1', sampleNumber: '42401', section: 'Cooking Peeling & Cutting',
        batchInfo: '150-12c-08/10-2211', batchNumber: '150-80-2211',
        brand: 'Costco', grade: '08/10', count: '10a', variety: 'EZPL',
        sampleSize: '10 gms', uniformity: '1:2', totalDefects: '10 gms -100%',
        finalResult: 'Pass', correctiveAction: 'Within spec limits',
        decomposition:       { value: 0.45, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShellLooseShell: { value: 0.26, pass: true  },
        sandVein:            { value: 0.22, pass: false },
        broken:              { value: 0.26, pass: true  },
        damaged:             { value: 0.22, pass: false },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.22, pass: false },
        legsShellSwimmerets: { value: 0.26, pass: true  },
        passFailSpec:        { value: 0.22, pass: false },
        correctiveActionSpec:{ value: 0.26, pass: true  },
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', sampleNumber: '42401', section: 'Cooking Peeling & Cutting',
        batchInfo: '150-12c-08/10-2211', batchNumber: '151-70-3322',
        brand: 'Walmart', grade: '08/11', count: '8b', variety: 'GRL',
        sampleSize: '8 gms', uniformity: '1:1', totalDefects: '8 gms -85%',
        finalResult: 'Fail', correctiveAction: 'Grill temp low',
        decomposition:       { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        softShellLooseShell: { value: 0.22, pass: false },
        sandVein:            { value: 0.26, pass: true  },
        broken:              { value: 0.22, pass: false },
        damaged:             { value: 0.26, pass: true  },
        blackTail:           { value: 0.22, pass: false },
        blackSpots:          { value: 0.26, pass: true  },
        legsShellSwimmerets: { value: 0.22, pass: false },
        passFailSpec:        { value: 0.26, pass: true  },
        correctiveActionSpec:{ value: 0.22, pass: false },
        brokenDamaged:       { value: 0.37, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3', sampleNumber: '42401', section: 'Cooking Peeling & Cutting',
        batchInfo: '150-12c-08/10-2211', batchNumber: '152-60-4433',
        brand: 'Target', grade: '08/12', count: '12c', variety: 'BAK',
        sampleSize: '1 kg', uniformity: '1:3', totalDefects: '1 kg -100%',
        finalResult: 'Pass', correctiveAction: 'Clean batch',
        decomposition:       { value: 0.47, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShellLooseShell: { value: 0.26, pass: true  },
        sandVein:            { value: 0.22, pass: false },
        broken:              { value: 0.26, pass: true  },
        damaged:             { value: 0.22, pass: false },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.22, pass: false },
        legsShellSwimmerets: { value: 0.26, pass: true  },
        passFailSpec:        { value: 0.22, pass: false },
        correctiveActionSpec:{ value: 0.26, pass: true  },
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4', sampleNumber: '42401', section: 'Cooking Peeling & Cutting',
        batchInfo: '150-12c-08/10-2211', batchNumber: '153-50-5544',
        brand: 'Kroger', grade: '08/13', count: '1pc', variety: 'FRY',
        sampleSize: '500 gms', uniformity: '2:1', totalDefects: '500 gms -95%',
        finalResult: 'Fail', correctiveAction: 'Black spots on shrimp',
        decomposition:       { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        softShellLooseShell: { value: 0.22, pass: false },
        sandVein:            { value: 0.26, pass: true  },
        broken:              { value: 0.22, pass: false },
        damaged:             { value: 0.26, pass: true  },
        blackTail:           { value: 0.22, pass: false },
        blackSpots:          { value: 0.09, pass: false },
        legsShellSwimmerets: { value: 0.26, pass: true  },
        passFailSpec:        { value: 0.22, pass: false },
        correctiveActionSpec:{ value: 0.26, pass: true  },
        brokenDamaged:       { value: 0.32, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5', sampleNumber: '42401', section: 'Cooking Peeling & Cutting',
        batchInfo: '150-12c-08/10-2211', batchNumber: '154-40-6655',
        brand: 'Whole Foods', grade: '08/14', count: '2pc', variety: 'STM',
        sampleSize: '1 kg', uniformity: '1:2', totalDefects: '1 kg -100%',
        finalResult: 'Pass', correctiveAction: 'Minimal defects',
        decomposition:       { value: 0.41, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShellLooseShell: { value: 0.26, pass: true  },
        sandVein:            { value: 0.22, pass: false },
        broken:              { value: 0.26, pass: true  },
        damaged:             { value: 0.22, pass: false },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.22, pass: false },
        legsShellSwimmerets: { value: 0.26, pass: true  },
        passFailSpec:        { value: 0.22, pass: false },
        correctiveActionSpec:{ value: 0.26, pass: true  },
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6', sampleNumber: '42401', section: 'Cooking Peeling & Cutting',
        batchInfo: '150-12c-08/10-2211', batchNumber: '155-30-7766',
        brand: "Sam's Club", grade: '08/15', count: '3pc', variety: 'CHB',
        sampleSize: '500 gms', uniformity: '1:1', totalDefects: '500 gms -90%',
        finalResult: 'Fail', correctiveAction: 'Mud smell detected',
        decomposition:       { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        softShellLooseShell: { value: 0.22, pass: false },
        sandVein:            { value: 0.26, pass: true  },
        broken:              { value: 0.22, pass: false },
        damaged:             { value: 0.26, pass: true  },
        blackTail:           { value: 0.22, pass: false },
        blackSpots:          { value: 0.26, pass: true  },
        legsShellSwimmerets: { value: 0.22, pass: false },
        passFailSpec:        { value: 0.26, pass: true  },
        correctiveActionSpec:{ value: 0.22, pass: false },
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.08, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7', sampleNumber: '42401', section: 'Cooking Peeling & Cutting',
        batchInfo: '150-12c-08/10-2211', batchNumber: '156-20-8877',
        brand: "Trader Joe's", grade: '08/16', count: '1pc', variety: 'EZPL',
        sampleSize: '12 gms', uniformity: '1:2', totalDefects: '12 gms -100%',
        finalResult: 'Pass', correctiveAction: 'Premium quality',
        decomposition:       { value: 0.52, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        softShellLooseShell: { value: 0.26, pass: true  },
        sandVein:            { value: 0.22, pass: false },
        broken:              { value: 0.26, pass: true  },
        damaged:             { value: 0.22, pass: false },
        blackTail:           { value: 0.26, pass: true  },
        blackSpots:          { value: 0.22, pass: false },
        legsShellSwimmerets: { value: 0.26, pass: true  },
        passFailSpec:        { value: 0.22, pass: false },
        correctiveActionSpec:{ value: 0.26, pass: true  },
        brokenDamaged:       { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCut:            { value: 0.22, pass: false },
        uncutSpec:           { value: 0.26, pass: true  },
        brokenTailSpec:      { value: 0.22, pass: false },
        chippedTailSpec:     { value: 0.26, pass: true  },
        muddySmellSpec:      { value: 0.22, pass: false },
        parasitesSpec:       { value: 0.26, pass: true  },
        foreignMatterSpec:   { value: 0.22, pass: false },
        presenceOfMetal:     { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
    ],
  },
};

export default CookingPeelingCuttingConfig;
