const FrozenCookedIQFConfig = {
  baseCols: [
    { key: 'section',        label: 'Section'                      },
    { key: 'grade',          label: 'Grade'                        },
    { key: 'variety',        label: 'Variety'                      },
    { key: 'brand',          label: 'Brand'                        },
    { key: 'packingStyle',   label: 'Packing Style'                },
    { key: 'deglazedWeight', label: 'Deglazed Weight'              },
    { key: 'stickWeight',    label: 'Stick Weight'                 },
    { key: 'totalPieces',    label: 'Total Pieces'                 },
    { key: 'weightBigSmall', label: "Weight (Kg's) (Big/Small)"    },
    { key: 'uniformity',     label: 'Uniformity'                   },
    { key: 'netCount',       label: 'Net Count'                    },
    { key: 'freezer',        label: 'Freezer'                      },
    { key: 'photo',          label: 'Photo',   type: 'photo'       },
    { key: 'prodMetSpec',    label: 'Prod.Met.Spec.', type: 'passFail' },
    { key: 'supervisor',     label: 'Supervisor'                   },
    { key: 'teamLeader',     label: 'Team Leader'                  },
    { key: 'remarks',        label: 'Remarks'                      },
  ],
  extraCols: [],
  valueCols: [
    { key: 'dehydration',        label: 'Dehydration (Spec)'           },
    { key: 'discoloration',      label: 'Discoloration (Spec)'         },
    { key: 'damagedBroken',      label: 'Damaged/Broken (Spec)'        },
    { key: 'sandVeinsPresent',   label: 'Sand Veins Present (Spec)'    },
    { key: 'blackspotTail',      label: 'Blackspot/Tail (Spec)'        },
    { key: 'brokenChippedTail',  label: 'Broken/Chipped Tail (Spec)'   },
    { key: 'softTailLooseShell', label: 'Soft Tail/Loose Shell (Spec)' },
    { key: 'hangingMeatNeckMeat',label: 'Hanging Meat/Neck Meat (Spec)'},
    { key: 'wrongCutUncut',      label: 'Wrong Cut/Uncut (Spec)'       },
    { key: 'clumps',             label: 'Clumps (Spec)'                },
  ],
  actionLabel: 'Action',
  data: {
    'pre-harvest': [
      {
        key: '1', section: 'Peel & Cut', grade: '12/14', variety: 'EZPL', brand: 'Costco',
        packingStyle: '6*5 Lbs', deglazedWeight: 'Short Weight', stickWeight: '0.5 grams',
        totalPieces: 6, weightBigSmall: '3000/200', uniformity: '3:2', netCount: 'Low Count',
        freezer: 'IQF-3', prodMetSpec: 'Pass', supervisor: 'Rahul', teamLeader: 'Revi',
        remarks: 'Shrimp has Dark Spots',
        dehydration:         { value: 0.49, pass: true  },
        discoloration:       { value: 0.10, pass: false },
        damagedBroken:       { value: 0.33, pass: true  },
        sandVeinsPresent:    { value: 0.49, pass: true  },
        blackspotTail:       { value: 0.28, pass: false },
        brokenChippedTail:   { value: 0.49, pass: true  },
        softTailLooseShell:  { value: 0.34, pass: true  },
        hangingMeatNeckMeat: { value: 4.62, pass: true  },
        wrongCutUncut:       { value: 1.45, pass: false },
        clumps:              { value: 0.49, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', section: 'Beheading', grade: '10/12', variety: 'FRESH', brand: 'Walmart',
        packingStyle: '4*7 Lbs', deglazedWeight: 'Excess Weight', stickWeight: '0.3 grams',
        totalPieces: 8, weightBigSmall: '1500/100', uniformity: '15:1', netCount: 'Over Count',
        freezer: 'IQF-2', prodMetSpec: 'Pass', supervisor: 'Sofia', teamLeader: 'Yang',
        remarks: 'Shrimp has Shell',
        dehydration:         { value: 0.26, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        damagedBroken:       { value: 0.26, pass: true  },
        sandVeinsPresent:    { value: 0.22, pass: false },
        blackspotTail:       { value: 0.26, pass: true  },
        brokenChippedTail:   { value: 0.22, pass: false },
        softTailLooseShell:  { value: 0.26, pass: true  },
        hangingMeatNeckMeat: { value: 0.22, pass: false },
        wrongCutUncut:       { value: 0.26, pass: true  },
        clumps:              { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '3', section: 'Grading', grade: '8/10', variety: 'FROZEN', brand: 'Target',
        packingStyle: '5*6 Lbs', deglazedWeight: 'Short Weight', stickWeight: '0.4 grams',
        totalPieces: 5, weightBigSmall: '2000/150', uniformity: '2:1.2', netCount: 'Low Count',
        freezer: 'IQF-1', prodMetSpec: 'Fail', supervisor: 'Michael', teamLeader: 'Lee',
        remarks: 'Shrimp has Color issue',
        dehydration:         { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        damagedBroken:       { value: 0.22, pass: false },
        sandVeinsPresent:    { value: 0.26, pass: true  },
        blackspotTail:       { value: 0.22, pass: false },
        brokenChippedTail:   { value: 0.26, pass: true  },
        softTailLooseShell:  { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCutUncut:       { value: 0.22, pass: false },
        clumps:              { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '4', section: 'Packing', grade: '14/16', variety: 'FRESH', brand: 'Kroger',
        packingStyle: '3*8 Lbs', deglazedWeight: 'Excess Weight', stickWeight: '0.2 grams',
        totalPieces: 10, weightBigSmall: '2500/180', uniformity: '2:1.1', netCount: 'Low Count',
        freezer: 'IQF-4', prodMetSpec: 'Pass', supervisor: 'Emily', teamLeader: 'Khan',
        remarks: 'Shrimp is Off-Color',
        dehydration:         { value: 0.26, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        damagedBroken:       { value: 0.26, pass: true  },
        sandVeinsPresent:    { value: 0.22, pass: false },
        blackspotTail:       { value: 0.26, pass: true  },
        brokenChippedTail:   { value: 0.22, pass: false },
        softTailLooseShell:  { value: 0.26, pass: true  },
        hangingMeatNeckMeat: { value: 0.22, pass: false },
        wrongCutUncut:       { value: 0.26, pass: true  },
        clumps:              { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '5', section: 'Beheading', grade: '6/8', variety: 'EZPL', brand: 'Whole Foods',
        packingStyle: '7*3 Lbs', deglazedWeight: 'Excess Weight', stickWeight: '0.6 grams',
        totalPieces: 4, weightBigSmall: '3500/220', uniformity: '3:0.2', netCount: 'Over Count',
        freezer: 'IQF-5', prodMetSpec: 'Fail', supervisor: 'David', teamLeader: 'Smith',
        remarks: 'Shrimp has Frost',
        dehydration:         { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        damagedBroken:       { value: 0.22, pass: false },
        sandVeinsPresent:    { value: 0.26, pass: true  },
        blackspotTail:       { value: 0.22, pass: false },
        brokenChippedTail:   { value: 0.26, pass: true  },
        softTailLooseShell:  { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCutUncut:       { value: 0.22, pass: false },
        clumps:              { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '6', section: 'Peel & Cut', grade: '16/18', variety: 'FROZEN', brand: "Sam's Club",
        packingStyle: '8*2 Lbs', deglazedWeight: 'Short Weight', stickWeight: '0.1 grams',
        totalPieces: 2, weightBigSmall: '4000/250', uniformity: '4:0.5', netCount: 'Low Count',
        freezer: 'IQF-6', prodMetSpec: 'Pass', supervisor: 'Laura', teamLeader: 'Choi',
        remarks: 'Shrimp has Ice',
        dehydration:         { value: 0.26, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        damagedBroken:       { value: 0.26, pass: true  },
        sandVeinsPresent:    { value: 0.22, pass: false },
        blackspotTail:       { value: 0.26, pass: true  },
        brokenChippedTail:   { value: 0.22, pass: false },
        softTailLooseShell:  { value: 0.26, pass: true  },
        hangingMeatNeckMeat: { value: 0.22, pass: false },
        wrongCutUncut:       { value: 0.26, pass: true  },
        clumps:              { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '7', section: 'Grading', grade: '21/25', variety: 'EZPL', brand: "Trader Joe's",
        packingStyle: '5*5 Lbs', deglazedWeight: 'Short Weight', stickWeight: '0.7 grams',
        totalPieces: 7, weightBigSmall: '1800/130', uniformity: '2:0.8', netCount: 'Low Count',
        freezer: 'IQF-7', prodMetSpec: 'Fail', supervisor: 'James', teamLeader: 'Park',
        remarks: 'Shrimp has Breakage',
        dehydration:         { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        damagedBroken:       { value: 0.22, pass: false },
        sandVeinsPresent:    { value: 0.26, pass: true  },
        blackspotTail:       { value: 0.22, pass: false },
        brokenChippedTail:   { value: 0.26, pass: true  },
        softTailLooseShell:  { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCutUncut:       { value: 0.22, pass: false },
        clumps:              { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
    ],
    'processing': [
      {
        key: '1', section: 'Grading', grade: '12/14', variety: 'H-Less', brand: 'Costco',
        packingStyle: '6*4 Lbs', deglazedWeight: 'Short Weight', stickWeight: '0.4 grams',
        totalPieces: 7, weightBigSmall: '2800/190', uniformity: '2:1.5', netCount: 'Low Count',
        freezer: 'IQF-1', prodMetSpec: 'Pass', supervisor: 'Rahul', teamLeader: 'Revi',
        remarks: 'Consistent quality',
        dehydration:         { value: 0.44, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        damagedBroken:       { value: 0.26, pass: true  },
        sandVeinsPresent:    { value: 0.22, pass: false },
        blackspotTail:       { value: 0.26, pass: true  },
        brokenChippedTail:   { value: 0.22, pass: false },
        softTailLooseShell:  { value: 0.26, pass: true  },
        hangingMeatNeckMeat: { value: 0.22, pass: false },
        wrongCutUncut:       { value: 0.26, pass: true  },
        clumps:              { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', section: 'Soaking', grade: '10/12', variety: 'H-ON', brand: 'Walmart',
        packingStyle: '4*6 Lbs', deglazedWeight: 'Excess Weight', stickWeight: '0.3 grams',
        totalPieces: 9, weightBigSmall: '1600/110', uniformity: '14:1', netCount: 'Over Count',
        freezer: 'IQF-2', prodMetSpec: 'Fail', supervisor: 'Sofia', teamLeader: 'Yang',
        remarks: 'Sand veins visible',
        dehydration:         { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        damagedBroken:       { value: 0.22, pass: false },
        sandVeinsPresent:    { value: 0.08, pass: false },
        blackspotTail:       { value: 0.26, pass: true  },
        brokenChippedTail:   { value: 0.22, pass: false },
        softTailLooseShell:  { value: 0.26, pass: true  },
        hangingMeatNeckMeat: { value: 0.22, pass: false },
        wrongCutUncut:       { value: 0.26, pass: true  },
        clumps:              { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3', section: 'IQF', grade: '8/10', variety: 'H-Less', brand: 'Target',
        packingStyle: '5*4 Lbs', deglazedWeight: 'Short Weight', stickWeight: '0.5 grams',
        totalPieces: 5, weightBigSmall: '2100/160', uniformity: '2:1.3', netCount: 'Low Count',
        freezer: 'IQF-3', prodMetSpec: 'Pass', supervisor: 'Michael', teamLeader: 'Lee',
        remarks: 'Good uniformity',
        dehydration:         { value: 0.46, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        damagedBroken:       { value: 0.26, pass: true  },
        sandVeinsPresent:    { value: 0.22, pass: false },
        blackspotTail:       { value: 0.26, pass: true  },
        brokenChippedTail:   { value: 0.22, pass: false },
        softTailLooseShell:  { value: 0.26, pass: true  },
        hangingMeatNeckMeat: { value: 0.22, pass: false },
        wrongCutUncut:       { value: 0.26, pass: true  },
        clumps:              { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4', section: 'Beheading', grade: '14/16', variety: 'H-ON', brand: 'Kroger',
        packingStyle: '3*6 Lbs', deglazedWeight: 'Excess Weight', stickWeight: '0.2 grams',
        totalPieces: 11, weightBigSmall: '2600/185', uniformity: '2:0.9', netCount: 'Low Count',
        freezer: 'IQF-4', prodMetSpec: 'Fail', supervisor: 'Emily', teamLeader: 'Khan',
        remarks: 'Improper cut found',
        dehydration:         { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        damagedBroken:       { value: 0.22, pass: false },
        sandVeinsPresent:    { value: 0.26, pass: true  },
        blackspotTail:       { value: 0.09, pass: false },
        brokenChippedTail:   { value: 0.26, pass: true  },
        softTailLooseShell:  { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCutUncut:       { value: 0.22, pass: false },
        clumps:              { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5', section: 'Peeling & Cutting', grade: '6/8', variety: 'H-Less', brand: 'Whole Foods',
        packingStyle: '7*2 Lbs', deglazedWeight: 'Short Weight', stickWeight: '0.6 grams',
        totalPieces: 3, weightBigSmall: '3600/225', uniformity: '3:0.1', netCount: 'Over Count',
        freezer: 'IQF-5', prodMetSpec: 'Pass', supervisor: 'David', teamLeader: 'Smith',
        remarks: 'Clean batch',
        dehydration:         { value: 0.43, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        damagedBroken:       { value: 0.26, pass: true  },
        sandVeinsPresent:    { value: 0.22, pass: false },
        blackspotTail:       { value: 0.26, pass: true  },
        brokenChippedTail:   { value: 0.22, pass: false },
        softTailLooseShell:  { value: 0.26, pass: true  },
        hangingMeatNeckMeat: { value: 0.22, pass: false },
        wrongCutUncut:       { value: 0.26, pass: true  },
        clumps:              { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6', section: 'Packing', grade: '16/18', variety: 'H-ON', brand: "Sam's Club",
        packingStyle: '8*4 Lbs', deglazedWeight: 'Excess Weight', stickWeight: '0.1 grams',
        totalPieces: 6, weightBigSmall: '4100/255', uniformity: '4:0.3', netCount: 'Low Count',
        freezer: 'IQF-6', prodMetSpec: 'Fail', supervisor: 'Laura', teamLeader: 'Choi',
        remarks: 'Discoloration found',
        dehydration:         { value: 0.22, pass: false },
        discoloration:       { value: 0.09, pass: false },
        damagedBroken:       { value: 0.26, pass: true  },
        sandVeinsPresent:    { value: 0.22, pass: false },
        blackspotTail:       { value: 0.26, pass: true  },
        brokenChippedTail:   { value: 0.22, pass: false },
        softTailLooseShell:  { value: 0.26, pass: true  },
        hangingMeatNeckMeat: { value: 0.22, pass: false },
        wrongCutUncut:       { value: 0.26, pass: true  },
        clumps:              { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7', section: 'Nobashi', grade: '21/25', variety: 'H-Less', brand: "Trader Joe's",
        packingStyle: '5*3 Lbs', deglazedWeight: 'Short Weight', stickWeight: '0.8 grams',
        totalPieces: 8, weightBigSmall: '1900/140', uniformity: '2:0.7', netCount: 'Low Count',
        freezer: 'IQF-7', prodMetSpec: 'Pass', supervisor: 'James', teamLeader: 'Park',
        remarks: 'Premium batch',
        dehydration:         { value: 0.50, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        damagedBroken:       { value: 0.26, pass: true  },
        sandVeinsPresent:    { value: 0.22, pass: false },
        blackspotTail:       { value: 0.26, pass: true  },
        brokenChippedTail:   { value: 0.22, pass: false },
        softTailLooseShell:  { value: 0.26, pass: true  },
        hangingMeatNeckMeat: { value: 0.22, pass: false },
        wrongCutUncut:       { value: 0.26, pass: true  },
        clumps:              { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
    ],
    'others': [
      {
        key: '1', section: 'Final Check', grade: '12/14', variety: 'EZPL', brand: 'Costco',
        packingStyle: '6*5 Lbs', deglazedWeight: 'Short Weight', stickWeight: '0.5 grams',
        totalPieces: 6, weightBigSmall: '3000/200', uniformity: '3:2', netCount: 'Low Count',
        freezer: 'IQF-3', prodMetSpec: 'Pass', supervisor: 'Rahul', teamLeader: 'Revi',
        remarks: 'Within spec limits',
        dehydration:         { value: 0.45, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        damagedBroken:       { value: 0.26, pass: true  },
        sandVeinsPresent:    { value: 0.22, pass: false },
        blackspotTail:       { value: 0.26, pass: true  },
        brokenChippedTail:   { value: 0.22, pass: false },
        softTailLooseShell:  { value: 0.26, pass: true  },
        hangingMeatNeckMeat: { value: 0.22, pass: false },
        wrongCutUncut:       { value: 0.26, pass: true  },
        clumps:              { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', section: 'QC Check', grade: '10/12', variety: 'FRESH', brand: 'Walmart',
        packingStyle: '4*7 Lbs', deglazedWeight: 'Excess Weight', stickWeight: '0.3 grams',
        totalPieces: 8, weightBigSmall: '1500/100', uniformity: '15:1', netCount: 'Over Count',
        freezer: 'IQF-2', prodMetSpec: 'Fail', supervisor: 'Sofia', teamLeader: 'Yang',
        remarks: 'Loose shell found',
        dehydration:         { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        damagedBroken:       { value: 0.22, pass: false },
        sandVeinsPresent:    { value: 0.26, pass: true  },
        blackspotTail:       { value: 0.22, pass: false },
        brokenChippedTail:   { value: 0.26, pass: true  },
        softTailLooseShell:  { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCutUncut:       { value: 0.22, pass: false },
        clumps:              { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3', section: 'Final Check', grade: '8/10', variety: 'FROZEN', brand: 'Target',
        packingStyle: '5*6 Lbs', deglazedWeight: 'Short Weight', stickWeight: '0.4 grams',
        totalPieces: 5, weightBigSmall: '2000/150', uniformity: '2:1.2', netCount: 'Low Count',
        freezer: 'IQF-1', prodMetSpec: 'Pass', supervisor: 'Michael', teamLeader: 'Lee',
        remarks: 'Clean batch',
        dehydration:         { value: 0.47, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        damagedBroken:       { value: 0.26, pass: true  },
        sandVeinsPresent:    { value: 0.22, pass: false },
        blackspotTail:       { value: 0.26, pass: true  },
        brokenChippedTail:   { value: 0.22, pass: false },
        softTailLooseShell:  { value: 0.26, pass: true  },
        hangingMeatNeckMeat: { value: 0.22, pass: false },
        wrongCutUncut:       { value: 0.26, pass: true  },
        clumps:              { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4', section: 'QC Check', grade: '14/16', variety: 'FRESH', brand: 'Kroger',
        packingStyle: '3*8 Lbs', deglazedWeight: 'Excess Weight', stickWeight: '0.2 grams',
        totalPieces: 10, weightBigSmall: '2500/180', uniformity: '2:1.1', netCount: 'Low Count',
        freezer: 'IQF-4', prodMetSpec: 'Fail', supervisor: 'Emily', teamLeader: 'Khan',
        remarks: 'Blackspot detected',
        dehydration:         { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        damagedBroken:       { value: 0.22, pass: false },
        sandVeinsPresent:    { value: 0.26, pass: true  },
        blackspotTail:       { value: 0.09, pass: false },
        brokenChippedTail:   { value: 0.26, pass: true  },
        softTailLooseShell:  { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCutUncut:       { value: 0.22, pass: false },
        clumps:              { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5', section: 'Final Check', grade: '6/8', variety: 'EZPL', brand: 'Whole Foods',
        packingStyle: '7*3 Lbs', deglazedWeight: 'Short Weight', stickWeight: '0.6 grams',
        totalPieces: 4, weightBigSmall: '3500/220', uniformity: '3:0.2', netCount: 'Over Count',
        freezer: 'IQF-5', prodMetSpec: 'Pass', supervisor: 'David', teamLeader: 'Smith',
        remarks: 'Minimal defects',
        dehydration:         { value: 0.41, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        damagedBroken:       { value: 0.26, pass: true  },
        sandVeinsPresent:    { value: 0.22, pass: false },
        blackspotTail:       { value: 0.26, pass: true  },
        brokenChippedTail:   { value: 0.22, pass: false },
        softTailLooseShell:  { value: 0.26, pass: true  },
        hangingMeatNeckMeat: { value: 0.22, pass: false },
        wrongCutUncut:       { value: 0.26, pass: true  },
        clumps:              { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6', section: 'QC Check', grade: '16/18', variety: 'FROZEN', brand: "Sam's Club",
        packingStyle: '8*2 Lbs', deglazedWeight: 'Excess Weight', stickWeight: '0.1 grams',
        totalPieces: 2, weightBigSmall: '4000/250', uniformity: '4:0.5', netCount: 'Low Count',
        freezer: 'IQF-6', prodMetSpec: 'Fail', supervisor: 'Laura', teamLeader: 'Choi',
        remarks: 'Wrong cut found',
        dehydration:         { value: 0.22, pass: false },
        discoloration:       { value: 0.26, pass: true  },
        damagedBroken:       { value: 0.22, pass: false },
        sandVeinsPresent:    { value: 0.26, pass: true  },
        blackspotTail:       { value: 0.22, pass: false },
        brokenChippedTail:   { value: 0.26, pass: true  },
        softTailLooseShell:  { value: 0.22, pass: false },
        hangingMeatNeckMeat: { value: 0.26, pass: true  },
        wrongCutUncut:       { value: 0.08, pass: false },
        clumps:              { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7', section: 'Final Check', grade: '21/25', variety: 'EZPL', brand: "Trader Joe's",
        packingStyle: '5*5 Lbs', deglazedWeight: 'Short Weight', stickWeight: '0.7 grams',
        totalPieces: 7, weightBigSmall: '1800/130', uniformity: '2:0.8', netCount: 'Low Count',
        freezer: 'IQF-7', prodMetSpec: 'Pass', supervisor: 'James', teamLeader: 'Park',
        remarks: 'Premium quality',
        dehydration:         { value: 0.52, pass: true  },
        discoloration:       { value: 0.22, pass: false },
        damagedBroken:       { value: 0.26, pass: true  },
        sandVeinsPresent:    { value: 0.22, pass: false },
        blackspotTail:       { value: 0.26, pass: true  },
        brokenChippedTail:   { value: 0.22, pass: false },
        softTailLooseShell:  { value: 0.26, pass: true  },
        hangingMeatNeckMeat: { value: 0.22, pass: false },
        wrongCutUncut:       { value: 0.26, pass: true  },
        clumps:              { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
    ],
  },
};

export default FrozenCookedIQFConfig;
