const GradingOIConfig = {
  baseCols: [
    { key: 'sampleNumber',     label: 'Sample Number'            },
    { key: 'section',          label: 'Section'                   },
    { key: 'batchInfo',        label: 'Batch Info'                },
    { key: 'batchNumber',      label: 'Batch Number'              },
    { key: 'grade',            label: 'Grade'                     },
    { key: 'count',            label: 'Count'                     },
    { key: 'quantity',         label: 'Quantity'                  },
    { key: 'sampleSize',       label: 'Sample Size'               },
    { key: 'uniformity',       label: 'Uniformity'                },
    { key: 'photo',            label: 'Photo',      type: 'photo'    },
    { key: 'totalDefects',     label: 'Total Defects (gms)'       },
    { key: 'finalResult',      label: 'Final Result', type: 'passFail' },
    { key: 'correctiveAction', label: 'Corrective Action'         },
  ],
  extraCols: [],
  valueCols: [
    { key: 'decomposition',        label: 'Decomposition (Spec)'          },
    { key: 'discoloration',        label: 'Discoloration (Spec)'          },
    { key: 'softShellLooseShell',  label: 'Soft Shell/Loose Shell (Spec)' },
    { key: 'brokenDamaged',        label: 'Broken/Damaged (Spec)'         },
    { key: 'blackTail',            label: 'Black Tail (Spec)'             },
    { key: 'blackSpots',           label: 'Black Spots (Spec)'            },
    { key: 'passFailSpec',         label: 'Pass/Fail (Spec)'              },
    { key: 'correctiveActionSpec', label: 'Corrective Action (Spec)'      },
    { key: 'brokenTail',           label: 'Broken Tail (Spec)'            },
    { key: 'chippedTail',          label: 'Chipped Tail (Spec)'           },
    { key: 'hangingMeat',          label: 'Hanging Meat/Neck Meat (Spec)' },
    { key: 'foreignMatter',        label: 'Foreign Matter (Spec)'         },
    { key: 'fungusParasites',      label: 'Fungus/Parasites (Spec)'       },
    { key: 'presenceOfMetal',      label: 'Presence of Metal'             },
  ],
  actionLabel: 'Action',
  data: {
    'pre-harvest': [
      {
        key: '1',
        sampleNumber: '42213', section: 'Grading', batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-3214',
        grade: '12/14', count: '12c', quantity: 64583, sampleSize: '12 gms', uniformity: '1:2',
        totalDefects: '12 gms -100%', finalResult: 'Pass', correctiveAction: 'Shrimp has Dark Spots',
        decomposition:        { value: 0.49, pass: true  },
        discoloration:        { value: 0.10, pass: false },
        softShellLooseShell:  { value: 0.34, pass: true  },
        brokenDamaged:        { value: 0.34, pass: true  },
        blackTail:            { value: 0.34, pass: true  },
        blackSpots:           { value: 0.10, pass: false },
        passFailSpec:         { value: 0.33, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        chippedTail:          { value: 0.28, pass: false },
        hangingMeat:          { value: 0.22, pass: false },
        foreignMatter:        { value: 0.34, pass: true  },
        fungusParasites:      { value: 4.62, pass: true  },
        presenceOfMetal:      { value: 1.45, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2',
        sampleNumber: '42213', section: 'Grading', batchInfo: '125-13c-12/14-3214', batchNumber: '126-54-7891',
        grade: '12/15', count: '10c', quantity: 64584, sampleSize: '15 gms', uniformity: '1:3',
        totalDefects: '15 gms -80%', finalResult: 'Fail', correctiveAction: 'Shrimp has Soft Shell',
        decomposition:        { value: 0.26, pass: true  },
        discoloration:        { value: 0.28, pass: true  },
        softShellLooseShell:  { value: 0.22, pass: false },
        brokenDamaged:        { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.24, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenTail:           { value: 0.18, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.20, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        fungusParasites:      { value: 3.41, pass: true  },
        presenceOfMetal:      { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3',
        sampleNumber: '42213', section: 'Grading', batchInfo: '125-13c-12/14-3214', batchNumber: '127-45-6782',
        grade: '12/16', count: '14c', quantity: 64585, sampleSize: '10 gms', uniformity: '1:1',
        totalDefects: '10 gms -90%', finalResult: 'Pass', correctiveAction: 'Shrimp is Fresh',
        decomposition:        { value: 0.32, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        softShellLooseShell:  { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.30, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.18, pass: true  },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.24, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.31, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.29, pass: true  },
        fungusParasites:      { value: 3.75, pass: true  },
        presenceOfMetal:      { value: 0.88, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4',
        sampleNumber: '42213', section: 'Grading', batchInfo: '125-13c-12/14-3214', batchNumber: '128-34-5673',
        grade: '12/17', count: '8c', quantity: 64586, sampleSize: '20 gms', uniformity: '1:4',
        totalDefects: '20 gms -70%', finalResult: 'Fail', correctiveAction: 'Shrimp has Foreign Matter',
        decomposition:        { value: 0.26, pass: true  },
        discoloration:        { value: 0.15, pass: false },
        softShellLooseShell:  { value: 0.40, pass: true  },
        brokenDamaged:        { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        passFailSpec:         { value: 0.36, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenTail:           { value: 0.25, pass: true  },
        chippedTail:          { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.33, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        fungusParasites:      { value: 5.11, pass: true  },
        presenceOfMetal:      { value: 1.82, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5',
        sampleNumber: '42213', section: 'Grading', batchInfo: '125-13c-12/14-3214', batchNumber: '129-23-4564',
        grade: '12/18', count: '11c', quantity: 64587, sampleSize: '18 gms', uniformity: '1:5',
        totalDefects: '18 gms -85%', finalResult: 'Pass', correctiveAction: 'Shrimp is Slightly Discolored',
        decomposition:        { value: 0.41, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        softShellLooseShell:  { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.38, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.29, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        chippedTail:          { value: 0.22, pass: false },
        hangingMeat:          { value: 0.27, pass: true  },
        foreignMatter:        { value: 0.35, pass: true  },
        fungusParasites:      { value: 4.00, pass: true  },
        presenceOfMetal:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6',
        sampleNumber: '42213', section: 'Grading', batchInfo: '125-13c-12/14-3214', batchNumber: '130-12-3455',
        grade: '12/19', count: '9c', quantity: 64588, sampleSize: '14 gms', uniformity: '1:2',
        totalDefects: '14 gms -95%', finalResult: 'Fail', correctiveAction: 'Broken Shell Present',
        decomposition:        { value: 0.22, pass: false },
        discoloration:        { value: 0.12, pass: false },
        softShellLooseShell:  { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.26, pass: true  },
        blackTail:            { value: 0.30, pass: true  },
        blackSpots:           { value: 0.08, pass: false },
        passFailSpec:         { value: 0.31, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenTail:           { value: 0.22, pass: true  },
        chippedTail:          { value: 0.35, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        fungusParasites:      { value: 3.88, pass: true  },
        presenceOfMetal:      { value: 1.60, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7',
        sampleNumber: '42213', section: 'Grading', batchInfo: '125-13c-12/14-3214', batchNumber: '131-01-2346',
        grade: '12/20', count: '13c', quantity: 64589, sampleSize: '16 gms', uniformity: '1:3',
        totalDefects: '16 gms -75%', finalResult: 'Pass', correctiveAction: 'Good Quality Batch',
        decomposition:        { value: 0.55, pass: true  },
        discoloration:        { value: 0.33, pass: true  },
        softShellLooseShell:  { value: 0.28, pass: true  },
        brokenDamaged:        { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.14, pass: true  },
        passFailSpec:         { value: 0.37, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        chippedTail:          { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.41, pass: true  },
        fungusParasites:      { value: 3.88, pass: true  },
        presenceOfMetal:      { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
    ],
    'processing': [
      {
        key: '1',
        sampleNumber: '42301', section: 'Grading', batchInfo: '136-14c-10/12-1122', batchNumber: '136-70-1122',
        grade: '10/12', count: '10c', quantity: 58200, sampleSize: '12 gms', uniformity: '1:2',
        totalDefects: '12 gms -88%', finalResult: 'Pass', correctiveAction: 'Minor Dehydration Found',
        decomposition:        { value: 0.44, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        softShellLooseShell:  { value: 0.30, pass: true  },
        brokenDamaged:        { value: 0.26, pass: true  },
        blackTail:            { value: 0.38, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        passFailSpec:         { value: 0.28, pass: true  },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: true  },
        foreignMatter:        { value: 0.32, pass: true  },
        fungusParasites:      { value: 4.10, pass: true  },
        presenceOfMetal:      { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2',
        sampleNumber: '42301', section: 'Grading', batchInfo: '136-14c-10/12-1122', batchNumber: '137-60-2233',
        grade: '10/13', count: '8c', quantity: 51800, sampleSize: '15 gms', uniformity: '1:3',
        totalDefects: '15 gms -65%', finalResult: 'Fail', correctiveAction: 'Soft Shell Detected',
        decomposition:        { value: 0.26, pass: true  },
        discoloration:        { value: 0.09, pass: false },
        softShellLooseShell:  { value: 0.45, pass: false },
        brokenDamaged:        { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: true  },
        blackSpots:           { value: 0.11, pass: false },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenTail:           { value: 0.20, pass: false },
        chippedTail:          { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        fungusParasites:      { value: 3.55, pass: true  },
        presenceOfMetal:      { value: 1.30, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3',
        sampleNumber: '42301', section: 'Grading', batchInfo: '136-14c-10/12-1122', batchNumber: '138-50-3344',
        grade: '10/14', count: '12c', quantity: 62400, sampleSize: '10 gms', uniformity: '1:1',
        totalDefects: '10 gms -92%', finalResult: 'Pass', correctiveAction: 'Acceptable Batch',
        decomposition:        { value: 0.51, pass: true  },
        discoloration:        { value: 0.25, pass: true  },
        softShellLooseShell:  { value: 0.22, pass: false },
        brokenDamaged:        { value: 0.28, pass: true  },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        passFailSpec:         { value: 0.35, pass: true  },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.19, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.38, pass: true  },
        fungusParasites:      { value: 4.50, pass: true  },
        presenceOfMetal:      { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4',
        sampleNumber: '42301', section: 'Grading', batchInfo: '136-14c-10/12-1122', batchNumber: '139-40-4455',
        grade: '10/15', count: '7c', quantity: 45100, sampleSize: '20 gms', uniformity: '1:4',
        totalDefects: '20 gms -72%', finalResult: 'Fail', correctiveAction: 'Black Spots Found',
        decomposition:        { value: 0.22, pass: false },
        discoloration:        { value: 0.13, pass: false },
        softShellLooseShell:  { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.22, pass: false },
        blackTail:            { value: 0.24, pass: true  },
        blackSpots:           { value: 0.08, pass: false },
        passFailSpec:         { value: 0.27, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        chippedTail:          { value: 0.33, pass: false },
        hangingMeat:          { value: 0.18, pass: true  },
        foreignMatter:        { value: 0.26, pass: true  },
        fungusParasites:      { value: 3.80, pass: true  },
        presenceOfMetal:      { value: 1.75, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5',
        sampleNumber: '42301', section: 'Grading', batchInfo: '136-14c-10/12-1122', batchNumber: '140-30-5566',
        grade: '10/16', count: '11c', quantity: 59800, sampleSize: '18 gms', uniformity: '1:5',
        totalDefects: '18 gms -80%', finalResult: 'Pass', correctiveAction: 'Good Texture',
        decomposition:        { value: 0.46, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        softShellLooseShell:  { value: 0.32, pass: true  },
        brokenDamaged:        { value: 0.29, pass: true  },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        passFailSpec:         { value: 0.34, pass: true  },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        foreignMatter:        { value: 0.36, pass: true  },
        fungusParasites:      { value: 4.25, pass: true  },
        presenceOfMetal:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6',
        sampleNumber: '42301', section: 'Grading', batchInfo: '136-14c-10/12-1122', batchNumber: '141-20-6677',
        grade: '10/17', count: '9c', quantity: 53600, sampleSize: '14 gms', uniformity: '1:2',
        totalDefects: '14 gms -68%', finalResult: 'Fail', correctiveAction: 'Chipped Tail Found',
        decomposition:        { value: 0.22, pass: false },
        discoloration:        { value: 0.16, pass: false },
        softShellLooseShell:  { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.31, pass: true  },
        blackTail:            { value: 0.20, pass: true  },
        blackSpots:           { value: 0.09, pass: false },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.40, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        fungusParasites:      { value: 3.90, pass: true  },
        presenceOfMetal:      { value: 1.55, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7',
        sampleNumber: '42301', section: 'Grading', batchInfo: '136-14c-10/12-1122', batchNumber: '142-10-7788',
        grade: '10/18', count: '14c', quantity: 67300, sampleSize: '16 gms', uniformity: '1:3',
        totalDefects: '16 gms -95%', finalResult: 'Pass', correctiveAction: 'Batch Meets Standards',
        decomposition:        { value: 0.53, pass: true  },
        discoloration:        { value: 0.30, pass: true  },
        softShellLooseShell:  { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        passFailSpec:         { value: 0.38, pass: true  },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.24, pass: true  },
        foreignMatter:        { value: 0.40, pass: true  },
        fungusParasites:      { value: 4.80, pass: true  },
        presenceOfMetal:      { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
    ],
    'others': [
      {
        key: '1',
        sampleNumber: '42401', section: 'Grading', batchInfo: '150-12c-08/10-2211', batchNumber: '150-80-2211',
        grade: '08/10', count: '14c', quantity: 72100, sampleSize: '12 gms', uniformity: '1:2',
        totalDefects: '12 gms -94%', finalResult: 'Pass', correctiveAction: 'Within Spec Limits',
        decomposition:        { value: 0.47, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        softShellLooseShell:  { value: 0.33, pass: true  },
        brokenDamaged:        { value: 0.27, pass: true  },
        blackTail:            { value: 0.35, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        passFailSpec:         { value: 0.31, pass: true  },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        foreignMatter:        { value: 0.33, pass: true  },
        fungusParasites:      { value: 4.40, pass: true  },
        presenceOfMetal:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2',
        sampleNumber: '42401', section: 'Grading', batchInfo: '150-12c-08/10-2211', batchNumber: '151-70-3322',
        grade: '08/11', count: '9c', quantity: 55400, sampleSize: '15 gms', uniformity: '1:3',
        totalDefects: '15 gms -60%', finalResult: 'Fail', correctiveAction: 'Fungus Detected',
        decomposition:        { value: 0.22, pass: false },
        discoloration:        { value: 0.11, pass: false },
        softShellLooseShell:  { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.12, pass: false },
        passFailSpec:         { value: 0.22, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenTail:           { value: 0.16, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.19, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        fungusParasites:      { value: 5.80, pass: false },
        presenceOfMetal:      { value: 1.90, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3',
        sampleNumber: '42401', section: 'Grading', batchInfo: '150-12c-08/10-2211', batchNumber: '152-60-4433',
        grade: '08/12', count: '11c', quantity: 63700, sampleSize: '10 gms', uniformity: '1:1',
        totalDefects: '10 gms -87%', finalResult: 'Pass', correctiveAction: 'Clean Batch',
        decomposition:        { value: 0.50, pass: true  },
        discoloration:        { value: 0.26, pass: true  },
        softShellLooseShell:  { value: 0.35, pass: true  },
        brokenDamaged:        { value: 0.31, pass: true  },
        blackTail:            { value: 0.29, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        passFailSpec:         { value: 0.34, pass: true  },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        foreignMatter:        { value: 0.39, pass: true  },
        fungusParasites:      { value: 4.15, pass: true  },
        presenceOfMetal:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4',
        sampleNumber: '42401', section: 'Grading', batchInfo: '150-12c-08/10-2211', batchNumber: '153-50-5544',
        grade: '08/13', count: '7c', quantity: 46800, sampleSize: '20 gms', uniformity: '1:4',
        totalDefects: '20 gms -55%', finalResult: 'Fail', correctiveAction: 'Metal Presence Found',
        decomposition:        { value: 0.26, pass: true  },
        discoloration:        { value: 0.14, pass: false },
        softShellLooseShell:  { value: 0.22, pass: false },
        brokenDamaged:        { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.07, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        chippedTail:          { value: 0.38, pass: false },
        hangingMeat:          { value: 0.23, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        fungusParasites:      { value: 3.60, pass: true  },
        presenceOfMetal:      { value: 2.10, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5',
        sampleNumber: '42401', section: 'Grading', batchInfo: '150-12c-08/10-2211', batchNumber: '154-40-6655',
        grade: '08/14', count: '12c', quantity: 61200, sampleSize: '18 gms', uniformity: '1:5',
        totalDefects: '18 gms -78%', finalResult: 'Pass', correctiveAction: 'Minimal Defects',
        decomposition:        { value: 0.43, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        softShellLooseShell:  { value: 0.31, pass: true  },
        brokenDamaged:        { value: 0.25, pass: true  },
        blackTail:            { value: 0.33, pass: true  },
        blackSpots:           { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.30, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        chippedTail:          { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.37, pass: true  },
        fungusParasites:      { value: 4.30, pass: true  },
        presenceOfMetal:      { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6',
        sampleNumber: '42401', section: 'Grading', batchInfo: '150-12c-08/10-2211', batchNumber: '155-30-7766',
        grade: '08/15', count: '8c', quantity: 50500, sampleSize: '14 gms', uniformity: '1:2',
        totalDefects: '14 gms -70%', finalResult: 'Fail', correctiveAction: 'Discoloration Observed',
        decomposition:        { value: 0.26, pass: true  },
        discoloration:        { value: 0.08, pass: false },
        softShellLooseShell:  { value: 0.22, pass: false },
        brokenDamaged:        { value: 0.23, pass: true  },
        blackTail:            { value: 0.28, pass: true  },
        blackSpots:           { value: 0.10, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenTail:           { value: 0.17, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        foreignMatter:        { value: 0.26, pass: true  },
        fungusParasites:      { value: 3.70, pass: true  },
        presenceOfMetal:      { value: 1.40, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7',
        sampleNumber: '42401', section: 'Grading', batchInfo: '150-12c-08/10-2211', batchNumber: '156-20-8877',
        grade: '08/16', count: '13c', quantity: 69900, sampleSize: '16 gms', uniformity: '1:3',
        totalDefects: '16 gms -91%', finalResult: 'Pass', correctiveAction: 'Premium Grade Batch',
        decomposition:        { value: 0.52, pass: true  },
        discoloration:        { value: 0.27, pass: true  },
        softShellLooseShell:  { value: 0.36, pass: true  },
        brokenDamaged:        { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        passFailSpec:         { value: 0.39, pass: true  },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.21, pass: true  },
        foreignMatter:        { value: 0.42, pass: true  },
        fungusParasites:      { value: 4.70, pass: true  },
        presenceOfMetal:      { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
    ],
  },
};

export default GradingOIConfig;
