const NobashiConfig = {
  baseCols: [
    { key: 'sampleNumber',     label: 'Sample Number'       },
    { key: 'section',          label: 'Section'              },
    { key: 'batchInfo',        label: 'Batch Info'           },
    { key: 'batchNumber',      label: 'Batch Number'         },
    { key: 'brand',            label: 'Brand'                },
    { key: 'grade',            label: 'Grade'                },
    { key: 'count',            label: 'Count'                },
    { key: 'variety',          label: 'Variety'              },
    { key: 'sampleSize',       label: 'Sample Size'          },
    { key: 'color',            label: 'Color'                },
    { key: 'noPiecePack',      label: 'No. of Pieces/Pack'   },
    { key: 'targetWeight',     label: 'Target Weight'        },
    { key: 'netWeight',        label: 'Net Weight'           },
    { key: 'specs',            label: 'Specs',  type: 'specs' },
    { key: 'photo',            label: 'Photo',  type: 'photo' },
    { key: 'totalDefects',     label: 'Total Defects (gms)'  },
    { key: 'finalResult',      label: 'Final Result', type: 'passFail' },
    { key: 'correctiveAction', label: 'Corrective Action'    },
  ],
  extraCols: [],
  valueCols: [
    { key: 'deepCut',              label: 'Deep Cut (Spec)'          },
    { key: 'blackTail',            label: 'Black Tail (Spec)'        },
    { key: 'hangingMeatSpec',      label: 'Hanging Meat (Spec)'      },
    { key: 'improperPeeling',      label: 'Improper Peeling (Spec)'  },
    { key: 'brokenSpec',           label: 'Broken (Spec)'            },
    { key: 'sandVeins',            label: 'Sand Veins (Spec)'        },
    { key: 'passFailSpec',         label: 'Pass/Fail (Spec)'         },
    { key: 'correctiveActionSpec', label: 'Corrective Action'        },
    { key: 'looseShellTail',       label: 'Loose Shell/Tail (Spec)'  },
    { key: 'brokenTail',           label: 'Broken Tail (Spec)'       },
    { key: 'hangingMeat',          label: 'Hanging Meat (Spec)'      },
    { key: 'softlSpec',            label: 'Soft (Spec)'              },
    { key: 'discoloration',        label: 'Discoloration (Spec)'     },
  ],
  actionLabel: 'Action',
  data: {
    'pre-harvest': [
      {
        key: '1',
        sampleNumber: '42213', section: 'Nobashi', batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-3214',
        brand: 'Walmart', grade: '12/14', count: '12c', variety: 'EZPL', sampleSize: '12 gms',
        color: '#D9D9D9', noPiecePack: 5, targetWeight: '20 gms -100%', netWeight: '18 gms -90%',
        totalDefects: '12 gms -100%', finalResult: 'Pass', correctiveAction: 'Shrimp has Dark Spots',
        deepCut:              { value: 0.49, pass: true  },
        blackTail:            { value: 0.10, pass: false },
        hangingMeatSpec:      { value: 0.34, pass: true  },
        improperPeeling:      { value: 0.34, pass: true  },
        brokenSpec:           { value: 0.34, pass: true  },
        sandVeins:            { value: 0.34, pass: true  },
        passFailSpec:         { value: 0.10, pass: false },
        correctiveActionSpec: { value: 0.34, pass: true  },
        looseShellTail:       { value: 0.28, pass: false },
        brokenTail:           { value: 0.28, pass: false },
        hangingMeat:          { value: 0.28, pass: false },
        softlSpec:            { value: 0.34, pass: true  },
        discoloration:        { value: 0.34, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2',
        sampleNumber: '42213', section: 'Nobashi', batchInfo: '125-13c-12/14-3214', batchNumber: '125-45-6789',
        brand: 'Target', grade: '01/23', count: '15a', variety: 'DRFT', sampleSize: '15 gms',
        color: '#E3E3E3', noPiecePack: 7, targetWeight: '18 gms -95%', netWeight: '20 gms -85%',
        totalDefects: '15 gms -95%', finalResult: 'Pass', correctiveAction: 'Sushi rolls not uniform',
        deepCut:              { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        hangingMeatSpec:      { value: 0.26, pass: true  },
        improperPeeling:      { value: 0.22, pass: false },
        brokenSpec:           { value: 0.26, pass: true  },
        sandVeins:            { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        looseShellTail:       { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        softlSpec:            { value: 0.22, pass: false },
        discoloration:        { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '3',
        sampleNumber: '42213', section: 'Nobashi', batchInfo: '125-13c-12/14-3214', batchNumber: '125-89-2345',
        brand: 'Costco', grade: '03/25', count: '10b', variety: 'TBRK', sampleSize: '25 gms',
        color: '#A1A1A1', noPiecePack: 10, targetWeight: '25 gms -100%', netWeight: '20 gms -90%',
        totalDefects: '25 gms -100%', finalResult: 'Fail', correctiveAction: 'Tempura too oily',
        deepCut:              { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        hangingMeatSpec:      { value: 0.22, pass: false },
        improperPeeling:      { value: 0.26, pass: true  },
        brokenSpec:           { value: 0.22, pass: false },
        sandVeins:            { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        looseShellTail:       { value: 0.35, pass: false },
        brokenTail:           { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        softlSpec:            { value: 0.22, pass: false },
        discoloration:        { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '4',
        sampleNumber: '42213', section: 'Nobashi', batchInfo: '125-13c-12/14-3214', batchNumber: '125-54-9876',
        brand: 'Kroger', grade: '04/21', count: '20d', variety: 'SASH', sampleSize: '10 gms',
        color: '#B2B2B2', noPiecePack: 8, targetWeight: '10 gms -100%', netWeight: '15 gms -95%',
        totalDefects: '10 gms -100%', finalResult: 'Pass', correctiveAction: 'Sashimi fresh',
        deepCut:              { value: 0.44, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        hangingMeatSpec:      { value: 0.26, pass: true  },
        improperPeeling:      { value: 0.22, pass: false },
        brokenSpec:           { value: 0.26, pass: true  },
        sandVeins:            { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        looseShellTail:       { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        softlSpec:            { value: 0.22, pass: false },
        discoloration:        { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '5',
        sampleNumber: '42213', section: 'Nobashi', batchInfo: '125-13c-12/14-3214', batchNumber: '125-34-5678',
        brand: 'Safeway', grade: '05/30', count: '30c', variety: 'KATU', sampleSize: '12 gms',
        color: '#C5C5C5', noPiecePack: 6, targetWeight: '12 gms -100%', netWeight: '16 gms -80%',
        totalDefects: '12 gms -100%', finalResult: 'Pass', correctiveAction: 'Katsu crispy',
        deepCut:              { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        hangingMeatSpec:      { value: 0.26, pass: true  },
        improperPeeling:      { value: 0.22, pass: false },
        brokenSpec:           { value: 0.26, pass: true  },
        sandVeins:            { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        looseShellTail:       { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        softlSpec:            { value: 0.22, pass: false },
        discoloration:        { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6',
        sampleNumber: '42213', section: 'Nobashi', batchInfo: '125-13c-12/14-3214', batchNumber: '125-22-1111',
        brand: 'Albertsons', grade: '06/12', count: '25f', variety: 'MSOP', sampleSize: '15 gms',
        color: '#F0F0F0', noPiecePack: 9, targetWeight: '15 gms -100%', netWeight: '10 gms -95%',
        totalDefects: '15 gms -100%', finalResult: 'Pass', correctiveAction: 'Soup flavorful',
        deepCut:              { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        hangingMeatSpec:      { value: 0.22, pass: false },
        improperPeeling:      { value: 0.26, pass: true  },
        brokenSpec:           { value: 0.22, pass: false },
        sandVeins:            { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        looseShellTail:       { value: 0.22, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        softlSpec:            { value: 0.26, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '7',
        sampleNumber: '42213', section: 'Nobashi', batchInfo: '125-13c-12/14-3214', batchNumber: '125-11-2222',
        brand: "Trader Joe's", grade: '07/15', count: '18g', variety: 'NBSH', sampleSize: '18 gms',
        color: '#CCCCCC', noPiecePack: 11, targetWeight: '18 gms -90%', netWeight: '14 gms -85%',
        totalDefects: '18 gms -90%', finalResult: 'Fail', correctiveAction: 'Batter uneven coating',
        deepCut:              { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        hangingMeatSpec:      { value: 0.22, pass: false },
        improperPeeling:      { value: 0.26, pass: true  },
        brokenSpec:           { value: 0.22, pass: false },
        sandVeins:            { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        looseShellTail:       { value: 0.38, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        softlSpec:            { value: 0.26, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
    ],
    'processing': [
      {
        key: '1',
        sampleNumber: '42301', section: 'Nobashi', batchInfo: '136-14c-10/12-1122', batchNumber: '136-70-1122',
        brand: 'Costco', grade: '10/20', count: '14b', variety: 'EZPL', sampleSize: '14 gms',
        color: '#D0D0D0', noPiecePack: 6, targetWeight: '14 gms -95%', netWeight: '12 gms -88%',
        totalDefects: '14 gms -95%', finalResult: 'Pass', correctiveAction: 'Consistent batch quality',
        deepCut:              { value: 0.46, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        hangingMeatSpec:      { value: 0.26, pass: true  },
        improperPeeling:      { value: 0.22, pass: false },
        brokenSpec:           { value: 0.26, pass: true  },
        sandVeins:            { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        looseShellTail:       { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        softlSpec:            { value: 0.22, pass: false },
        discoloration:        { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2',
        sampleNumber: '42301', section: 'Nobashi', batchInfo: '136-14c-10/12-1122', batchNumber: '137-60-2233',
        brand: 'Walmart', grade: '02/18', count: '12c', variety: 'TBRK', sampleSize: '12 gms',
        color: '#E8E8E8', noPiecePack: 8, targetWeight: '12 gms -90%', netWeight: '10 gms -80%',
        totalDefects: '12 gms -90%', finalResult: 'Fail', correctiveAction: 'Deep cut too wide',
        deepCut:              { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        hangingMeatSpec:      { value: 0.22, pass: false },
        improperPeeling:      { value: 0.26, pass: true  },
        brokenSpec:           { value: 0.22, pass: false },
        sandVeins:            { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        looseShellTail:       { value: 0.31, pass: false },
        brokenTail:           { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        softlSpec:            { value: 0.22, pass: false },
        discoloration:        { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3',
        sampleNumber: '42301', section: 'Nobashi', batchInfo: '136-14c-10/12-1122', batchNumber: '138-50-3344',
        brand: 'Target', grade: '03/22', count: '16a', variety: 'DRFT', sampleSize: '16 gms',
        color: '#B8B8B8', noPiecePack: 10, targetWeight: '16 gms -100%', netWeight: '14 gms -92%',
        totalDefects: '16 gms -100%', finalResult: 'Pass', correctiveAction: 'Good uniformity',
        deepCut:              { value: 0.48, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        hangingMeatSpec:      { value: 0.26, pass: true  },
        improperPeeling:      { value: 0.22, pass: false },
        brokenSpec:           { value: 0.26, pass: true  },
        sandVeins:            { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        looseShellTail:       { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        softlSpec:            { value: 0.22, pass: false },
        discoloration:        { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4',
        sampleNumber: '42301', section: 'Nobashi', batchInfo: '136-14c-10/12-1122', batchNumber: '139-40-4455',
        brand: 'Kroger', grade: '04/19', count: '22d', variety: 'SASH', sampleSize: '10 gms',
        color: '#C0C0C0', noPiecePack: 7, targetWeight: '10 gms -95%', netWeight: '8 gms -85%',
        totalDefects: '10 gms -95%', finalResult: 'Fail', correctiveAction: 'Improper peeling found',
        deepCut:              { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        hangingMeatSpec:      { value: 0.22, pass: false },
        improperPeeling:      { value: 0.09, pass: false },
        brokenSpec:           { value: 0.26, pass: true  },
        sandVeins:            { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        looseShellTail:       { value: 0.34, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        softlSpec:            { value: 0.26, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5',
        sampleNumber: '42301', section: 'Nobashi', batchInfo: '136-14c-10/12-1122', batchNumber: '140-30-5566',
        brand: 'Safeway', grade: '05/24', count: '28f', variety: 'KATU', sampleSize: '20 gms',
        color: '#EBEBEB', noPiecePack: 5, targetWeight: '20 gms -100%', netWeight: '18 gms -90%',
        totalDefects: '20 gms -100%', finalResult: 'Pass', correctiveAction: 'Katsu batter perfect',
        deepCut:              { value: 0.41, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        hangingMeatSpec:      { value: 0.26, pass: true  },
        improperPeeling:      { value: 0.22, pass: false },
        brokenSpec:           { value: 0.26, pass: true  },
        sandVeins:            { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        looseShellTail:       { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        softlSpec:            { value: 0.22, pass: false },
        discoloration:        { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6',
        sampleNumber: '42301', section: 'Nobashi', batchInfo: '136-14c-10/12-1122', batchNumber: '141-20-6677',
        brand: 'Albertsons', grade: '06/16', count: '20c', variety: 'MSOP', sampleSize: '15 gms',
        color: '#F5F5F5', noPiecePack: 9, targetWeight: '15 gms -95%', netWeight: '12 gms -80%',
        totalDefects: '15 gms -95%', finalResult: 'Fail', correctiveAction: 'Sand veins visible',
        deepCut:              { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        hangingMeatSpec:      { value: 0.22, pass: false },
        improperPeeling:      { value: 0.26, pass: true  },
        brokenSpec:           { value: 0.22, pass: false },
        sandVeins:            { value: 0.08, pass: false },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        looseShellTail:       { value: 0.22, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        softlSpec:            { value: 0.26, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7',
        sampleNumber: '42301', section: 'Nobashi', batchInfo: '136-14c-10/12-1122', batchNumber: '142-10-7788',
        brand: "Trader Joe's", grade: '07/18', count: '15g', variety: 'NBSH', sampleSize: '18 gms',
        color: '#D5D5D5', noPiecePack: 12, targetWeight: '18 gms -100%', netWeight: '16 gms -95%',
        totalDefects: '18 gms -100%', finalResult: 'Pass', correctiveAction: 'Excellent batch',
        deepCut:              { value: 0.50, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        hangingMeatSpec:      { value: 0.26, pass: true  },
        improperPeeling:      { value: 0.22, pass: false },
        brokenSpec:           { value: 0.26, pass: true  },
        sandVeins:            { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        looseShellTail:       { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        softlSpec:            { value: 0.22, pass: false },
        discoloration:        { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
    ],
    'others': [
      {
        key: '1',
        sampleNumber: '42401', section: 'Nobashi', batchInfo: '150-12c-08/10-2211', batchNumber: '150-80-2211',
        brand: 'Costco', grade: '08/16', count: '10a', variety: 'EZPL', sampleSize: '10 gms',
        color: '#DEDEDE', noPiecePack: 6, targetWeight: '10 gms -100%', netWeight: '9 gms -90%',
        totalDefects: '10 gms -100%', finalResult: 'Pass', correctiveAction: 'Within spec limits',
        deepCut:              { value: 0.45, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        hangingMeatSpec:      { value: 0.26, pass: true  },
        improperPeeling:      { value: 0.22, pass: false },
        brokenSpec:           { value: 0.26, pass: true  },
        sandVeins:            { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        looseShellTail:       { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        softlSpec:            { value: 0.22, pass: false },
        discoloration:        { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2',
        sampleNumber: '42401', section: 'Nobashi', batchInfo: '150-12c-08/10-2211', batchNumber: '151-70-3322',
        brand: 'Walmart', grade: '02/14', count: '8b', variety: 'DRFT', sampleSize: '8 gms',
        color: '#E6E6E6', noPiecePack: 5, targetWeight: '8 gms -85%', netWeight: '7 gms -80%',
        totalDefects: '8 gms -85%', finalResult: 'Fail', correctiveAction: 'Loose shell found',
        deepCut:              { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        hangingMeatSpec:      { value: 0.22, pass: false },
        improperPeeling:      { value: 0.26, pass: true  },
        brokenSpec:           { value: 0.22, pass: false },
        sandVeins:            { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        looseShellTail:       { value: 0.37, pass: false },
        brokenTail:           { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        softlSpec:            { value: 0.22, pass: false },
        discoloration:        { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3',
        sampleNumber: '42401', section: 'Nobashi', batchInfo: '150-12c-08/10-2211', batchNumber: '152-60-4433',
        brand: 'Target', grade: '03/20', count: '12c', variety: 'TBRK', sampleSize: '12 gms',
        color: '#AFAFAF', noPiecePack: 8, targetWeight: '12 gms -100%', netWeight: '11 gms -92%',
        totalDefects: '12 gms -100%', finalResult: 'Pass', correctiveAction: 'Clean batch',
        deepCut:              { value: 0.47, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        hangingMeatSpec:      { value: 0.26, pass: true  },
        improperPeeling:      { value: 0.22, pass: false },
        brokenSpec:           { value: 0.26, pass: true  },
        sandVeins:            { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        looseShellTail:       { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        softlSpec:            { value: 0.22, pass: false },
        discoloration:        { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4',
        sampleNumber: '42401', section: 'Nobashi', batchInfo: '150-12c-08/10-2211', batchNumber: '153-50-5544',
        brand: 'Kroger', grade: '04/17', count: '18d', variety: 'SASH', sampleSize: '15 gms',
        color: '#BEBEBE', noPiecePack: 7, targetWeight: '15 gms -95%', netWeight: '13 gms -85%',
        totalDefects: '15 gms -95%', finalResult: 'Fail', correctiveAction: 'Black tail detected',
        deepCut:              { value: 0.22, pass: false },
        blackTail:            { value: 0.09, pass: false },
        hangingMeatSpec:      { value: 0.26, pass: true  },
        improperPeeling:      { value: 0.22, pass: false },
        brokenSpec:           { value: 0.26, pass: true  },
        sandVeins:            { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        looseShellTail:       { value: 0.32, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        softlSpec:            { value: 0.26, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5',
        sampleNumber: '42401', section: 'Nobashi', batchInfo: '150-12c-08/10-2211', batchNumber: '154-40-6655',
        brand: 'Safeway', grade: '05/22', count: '24f', variety: 'KATU', sampleSize: '20 gms',
        color: '#E0E0E0', noPiecePack: 11, targetWeight: '20 gms -100%', netWeight: '18 gms -90%',
        totalDefects: '20 gms -100%', finalResult: 'Pass', correctiveAction: 'Minimal defects',
        deepCut:              { value: 0.43, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        hangingMeatSpec:      { value: 0.26, pass: true  },
        improperPeeling:      { value: 0.22, pass: false },
        brokenSpec:           { value: 0.26, pass: true  },
        sandVeins:            { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        looseShellTail:       { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        softlSpec:            { value: 0.22, pass: false },
        discoloration:        { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6',
        sampleNumber: '42401', section: 'Nobashi', batchInfo: '150-12c-08/10-2211', batchNumber: '155-30-7766',
        brand: 'Albertsons', grade: '06/10', count: '20c', variety: 'MSOP', sampleSize: '10 gms',
        color: '#F2F2F2', noPiecePack: 6, targetWeight: '10 gms -90%', netWeight: '9 gms -85%',
        totalDefects: '10 gms -90%', finalResult: 'Fail', correctiveAction: 'Discoloration observed',
        deepCut:              { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        hangingMeatSpec:      { value: 0.22, pass: false },
        improperPeeling:      { value: 0.26, pass: true  },
        brokenSpec:           { value: 0.22, pass: false },
        sandVeins:            { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        looseShellTail:       { value: 0.22, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        softlSpec:            { value: 0.09, pass: false },
        discoloration:        { value: 0.08, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7',
        sampleNumber: '42401', section: 'Nobashi', batchInfo: '150-12c-08/10-2211', batchNumber: '156-20-8877',
        brand: "Trader Joe's", grade: '07/14', count: '16g', variety: 'NBSH', sampleSize: '16 gms',
        color: '#D8D8D8', noPiecePack: 10, targetWeight: '16 gms -100%', netWeight: '15 gms -95%',
        totalDefects: '16 gms -100%', finalResult: 'Pass', correctiveAction: 'Premium quality',
        deepCut:              { value: 0.52, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        hangingMeatSpec:      { value: 0.26, pass: true  },
        improperPeeling:      { value: 0.22, pass: false },
        brokenSpec:           { value: 0.26, pass: true  },
        sandVeins:            { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        looseShellTail:       { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        softlSpec:            { value: 0.22, pass: false },
        discoloration:        { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
    ],
  },
};

export default NobashiConfig;
