const PeelingCuttingConfig = {
  baseCols: [
    { key: 'sampleNumber',     label: 'Sample Number'            },
    { key: 'section',          label: 'Section'                   },
    { key: 'batchInfo',        label: 'Batch Info'                },
    { key: 'batchNumber',      label: 'Batch Number'              },
    { key: 'brand',            label: 'Brand'                     },
    { key: 'grade',            label: 'Grade'                     },
    { key: 'count',            label: 'Count'                     },
    { key: 'variety',          label: 'Variety'                   },
    { key: 'sampleSize',       label: 'Sample Size'               },
    { key: 'uniformity',       label: 'Uniformity'                },
    { key: 'photo',            label: 'Photo',      type: 'photo'    },
    { key: 'totalDefects',     label: 'Total Defects (gms)'       },
    { key: 'finalResult',      label: 'Final Result', type: 'passFail' },
    { key: 'correctiveAction', label: 'Corrective Action'         },
  ],
  extraCols: [],
  valueCols: [
    { key: 'decomposition',        label: 'Decomposition (Spec)'          },
    { key: 'discoloration',        label: 'Discoloration (Spec)'          },
    { key: 'softShellLooseShell',  label: 'Soft Shell/Loose Shell (Spec)' },
    { key: 'sandVein',             label: 'Sand Vein (Spec)'              },
    { key: 'blackTail',            label: 'Black Tail (Spec)'             },
    { key: 'blackSpots',           label: 'Black Spots (Spec)'            },
    { key: 'legsShellSwimmerets',  label: 'Legs/Shell/Swimmerets'         },
    { key: 'passFailSpec',         label: 'Pass/Fail (Spec)'              },
    { key: 'correctiveActionSpec', label: 'Corrective Action (Spec)'      },
    { key: 'brokenDamaged',        label: 'Broken/Damaged'                },
    { key: 'hangingMeat',          label: 'Hanging Meat/Neck Meat (Spec)' },
    { key: 'wrongCut',             label: 'Wrong Cut'                     },
    { key: 'brokenTail',           label: 'Broken Tail (Spec)'            },
    { key: 'chippedTail',          label: 'Chipped Tail (Spec)'           },
    { key: 'foreignMatter',        label: 'Foreign Matter (Spec)'         },
    { key: 'fungusParasites',      label: 'Fungus/Parasites (Spec)'       },
    { key: 'presenceOfMetal',      label: 'Presence of Metal'             },
  ],
  actionLabel: 'Action',
  data: {
    'pre-harvest': [
      {
        key: '1',
        sampleNumber: '42213', section: 'Peeling & Cutting', batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-3214',
        brand: 'Walmart', grade: '12/14', count: '12c', variety: 'EZPL', sampleSize: '12 gms', uniformity: '1:2',
        totalDefects: '12 gms -100%', finalResult: 'Pass', correctiveAction: 'Shrimp has Dark Spots',
        decomposition:        { value: 0.49, pass: true  },
        discoloration:        { value: 0.10, pass: false },
        softShellLooseShell:  { value: 0.34, pass: true  },
        sandVein:             { value: 0.34, pass: true  },
        blackTail:            { value: 0.34, pass: true  },
        blackSpots:           { value: 0.10, pass: false },
        legsShellSwimmerets:  { value: 0.10, pass: false },
        passFailSpec:         { value: 0.33, pass: true  },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.28, pass: false },
        hangingMeat:          { value: 0.22, pass: false },
        wrongCut:             { value: 0.34, pass: true  },
        brokenTail:           { value: 0.33, pass: true  },
        chippedTail:          { value: 0.33, pass: true  },
        foreignMatter:        { value: 0.34, pass: true  },
        fungusParasites:      { value: 4.62, pass: true  },
        presenceOfMetal:      { value: 1.45, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2',
        sampleNumber: '42213', section: 'Peeling & Cutting', batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-3215',
        brand: 'Target', grade: '12/15', count: '10c', variety: 'EZPL', sampleSize: '10 gms', uniformity: '1:3',
        totalDefects: '10 gms -90%', finalResult: 'Pass', correctiveAction: 'Chicken is Fresh',
        decomposition:        { value: 0.26, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        softShellLooseShell:  { value: 0.30, pass: true  },
        sandVein:             { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        legsShellSwimmerets:  { value: 0.22, pass: false },
        passFailSpec:         { value: 0.28, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:        { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        wrongCut:             { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        fungusParasites:      { value: 3.41, pass: true  },
        presenceOfMetal:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '3',
        sampleNumber: '42213', section: 'Peeling & Cutting', batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-3216',
        brand: 'Costco', grade: '12/16', count: '8c', variety: 'EZPL', sampleSize: '8 gms', uniformity: '1:4',
        totalDefects: '8 gms -80%', finalResult: 'Fail', correctiveAction: 'Beef has Unpleasant Odor',
        decomposition:        { value: 0.22, pass: false },
        discoloration:        { value: 0.18, pass: false },
        softShellLooseShell:  { value: 0.26, pass: true  },
        sandVein:             { value: 0.22, pass: false },
        blackTail:            { value: 0.30, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        legsShellSwimmerets:  { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.35, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        wrongCut:             { value: 0.22, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        chippedTail:          { value: 0.22, pass: false },
        foreignMatter:        { value: 0.26, pass: true  },
        fungusParasites:      { value: 5.11, pass: true  },
        presenceOfMetal:      { value: 1.82, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '4',
        sampleNumber: '42213', section: 'Peeling & Cutting', batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-3217',
        brand: 'Kroger', grade: '12/17', count: '15c', variety: 'EZPL', sampleSize: '15 gms', uniformity: '1:1',
        totalDefects: '15 gms -100%', finalResult: 'Pass', correctiveAction: 'Fish is Excellent',
        decomposition:        { value: 0.44, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        softShellLooseShell:  { value: 0.38, pass: true  },
        sandVein:             { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        legsShellSwimmerets:  { value: 0.22, pass: false },
        passFailSpec:         { value: 0.35, pass: true  },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        wrongCut:             { value: 0.31, pass: true  },
        brokenTail:           { value: 0.26, pass: true  },
        chippedTail:          { value: 0.22, pass: false },
        foreignMatter:        { value: 0.33, pass: true  },
        fungusParasites:      { value: 4.00, pass: true  },
        presenceOfMetal:      { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '5',
        sampleNumber: '42213', section: 'Peeling & Cutting', batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-3218',
        brand: 'Publix', grade: '12/18', count: '5c', variety: 'EZPL', sampleSize: '5 gms', uniformity: '1:5',
        totalDefects: '5 gms -70%', finalResult: 'Fail', correctiveAction: 'Pork has Discoloration',
        decomposition:        { value: 0.26, pass: true  },
        discoloration:        { value: 0.12, pass: false },
        softShellLooseShell:  { value: 0.22, pass: false },
        sandVein:             { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        legsShellSwimmerets:  { value: 0.14, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:        { value: 0.40, pass: false },
        hangingMeat:          { value: 0.22, pass: false },
        wrongCut:             { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        fungusParasites:      { value: 3.75, pass: true  },
        presenceOfMetal:      { value: 1.60, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '6',
        sampleNumber: '42213', section: 'Peeling & Cutting', batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-3219',
        brand: 'Whole Foods', grade: '12/19', count: '9c', variety: 'EZPL', sampleSize: '9 gms', uniformity: '1:2',
        totalDefects: '9 gms -85%', finalResult: 'Pass', correctiveAction: 'Good Quality Shrimp',
        decomposition:        { value: 0.51, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        softShellLooseShell:  { value: 0.32, pass: true  },
        sandVein:             { value: 0.22, pass: false },
        blackTail:            { value: 0.29, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        legsShellSwimmerets:  { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.30, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:        { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        wrongCut:             { value: 0.33, pass: true  },
        brokenTail:           { value: 0.26, pass: true  },
        chippedTail:          { value: 0.22, pass: false },
        foreignMatter:        { value: 0.29, pass: true  },
        fungusParasites:      { value: 4.30, pass: true  },
        presenceOfMetal:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '7',
        sampleNumber: '42213', section: 'Peeling & Cutting', batchInfo: '125-13c-12/14-3214', batchNumber: '125-65-3220',
        brand: "Sam's Club", grade: '12/20', count: '11c', variety: 'EZPL', sampleSize: '11 gms', uniformity: '1:3',
        totalDefects: '11 gms -75%', finalResult: 'Fail', correctiveAction: 'Sand Vein Found',
        decomposition:        { value: 0.22, pass: false },
        discoloration:        { value: 0.16, pass: false },
        softShellLooseShell:  { value: 0.26, pass: true  },
        sandVein:             { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.09, pass: false },
        legsShellSwimmerets:  { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:        { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.26, pass: true  },
        wrongCut:             { value: 0.22, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        chippedTail:          { value: 0.22, pass: false },
        foreignMatter:        { value: 0.26, pass: true  },
        fungusParasites:      { value: 3.88, pass: true  },
        presenceOfMetal:      { value: 1.30, pass: false },
        status: 'Fail', action: 'Rejected',
      },
    ],
    'processing': [
      {
        key: '1',
        sampleNumber: '42301', section: 'Peeling & Cutting', batchInfo: '136-14c-10/12-1122', batchNumber: '136-70-1122',
        brand: 'Costco', grade: '10/12', count: '10c', variety: 'H-Less', sampleSize: '10 gms', uniformity: '1:2',
        totalDefects: '10 gms -88%', finalResult: 'Pass', correctiveAction: 'Acceptable Quality',
        decomposition:        { value: 0.46, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        softShellLooseShell:  { value: 0.28, pass: true  },
        sandVein:             { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        legsShellSwimmerets:  { value: 0.22, pass: false },
        passFailSpec:         { value: 0.32, pass: true  },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        wrongCut:             { value: 0.30, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.31, pass: true  },
        fungusParasites:      { value: 4.10, pass: true  },
        presenceOfMetal:      { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2',
        sampleNumber: '42301', section: 'Peeling & Cutting', batchInfo: '136-14c-10/12-1122', batchNumber: '137-60-2233',
        brand: 'Walmart', grade: '10/13', count: '8c', variety: 'H-ON', sampleSize: '8 gms', uniformity: '1:3',
        totalDefects: '8 gms -65%', finalResult: 'Fail', correctiveAction: 'Legs Found in Batch',
        decomposition:        { value: 0.22, pass: false },
        discoloration:        { value: 0.11, pass: false },
        softShellLooseShell:  { value: 0.26, pass: true  },
        sandVein:             { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.08, pass: false },
        legsShellSwimmerets:  { value: 0.14, pass: false },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.33, pass: false },
        hangingMeat:          { value: 0.22, pass: false },
        wrongCut:             { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        fungusParasites:      { value: 3.55, pass: true  },
        presenceOfMetal:      { value: 1.75, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3',
        sampleNumber: '42301', section: 'Peeling & Cutting', batchInfo: '136-14c-10/12-1122', batchNumber: '138-50-3344',
        brand: 'Target', grade: '10/14', count: '12c', variety: 'H-Less', sampleSize: '12 gms', uniformity: '1:1',
        totalDefects: '12 gms -92%', finalResult: 'Pass', correctiveAction: 'Clean Cut Batch',
        decomposition:        { value: 0.48, pass: true  },
        discoloration:        { value: 0.26, pass: true  },
        softShellLooseShell:  { value: 0.22, pass: false },
        sandVein:             { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        legsShellSwimmerets:  { value: 0.22, pass: false },
        passFailSpec:         { value: 0.34, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:        { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        wrongCut:             { value: 0.26, pass: true  },
        brokenTail:           { value: 0.29, pass: true  },
        chippedTail:          { value: 0.22, pass: false },
        foreignMatter:        { value: 0.26, pass: true  },
        fungusParasites:      { value: 4.50, pass: true  },
        presenceOfMetal:      { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4',
        sampleNumber: '42301', section: 'Peeling & Cutting', batchInfo: '136-14c-10/12-1122', batchNumber: '139-40-4455',
        brand: 'Kroger', grade: '10/15', count: '7c', variety: 'H-ON', sampleSize: '7 gms', uniformity: '1:4',
        totalDefects: '7 gms -72%', finalResult: 'Fail', correctiveAction: 'Wrong Cut Detected',
        decomposition:        { value: 0.22, pass: false },
        discoloration:        { value: 0.13, pass: false },
        softShellLooseShell:  { value: 0.26, pass: true  },
        sandVein:             { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.09, pass: false },
        legsShellSwimmerets:  { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.38, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        wrongCut:             { value: 0.22, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        chippedTail:          { value: 0.22, pass: false },
        foreignMatter:        { value: 0.22, pass: false },
        fungusParasites:      { value: 3.80, pass: true  },
        presenceOfMetal:      { value: 1.55, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5',
        sampleNumber: '42301', section: 'Peeling & Cutting', batchInfo: '136-14c-10/12-1122', batchNumber: '140-30-5566',
        brand: 'Whole Foods', grade: '10/16', count: '11c', variety: 'H-Less', sampleSize: '11 gms', uniformity: '1:5',
        totalDefects: '11 gms -80%', finalResult: 'Pass', correctiveAction: 'Good Texture',
        decomposition:        { value: 0.43, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        softShellLooseShell:  { value: 0.31, pass: true  },
        sandVein:             { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        legsShellSwimmerets:  { value: 0.22, pass: false },
        passFailSpec:         { value: 0.33, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:        { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        wrongCut:             { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.28, pass: true  },
        fungusParasites:      { value: 4.25, pass: true  },
        presenceOfMetal:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6',
        sampleNumber: '42301', section: 'Peeling & Cutting', batchInfo: '136-14c-10/12-1122', batchNumber: '141-20-6677',
        brand: "Sam's Club", grade: '10/17', count: '9c', variety: 'H-ON', sampleSize: '9 gms', uniformity: '1:2',
        totalDefects: '9 gms -68%', finalResult: 'Fail', correctiveAction: 'Shell Pieces Found',
        decomposition:        { value: 0.22, pass: false },
        discoloration:        { value: 0.15, pass: false },
        softShellLooseShell:  { value: 0.26, pass: true  },
        sandVein:             { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.10, pass: false },
        legsShellSwimmerets:  { value: 0.13, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:        { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        wrongCut:             { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        fungusParasites:      { value: 3.90, pass: true  },
        presenceOfMetal:      { value: 1.40, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7',
        sampleNumber: '42301', section: 'Peeling & Cutting', batchInfo: '136-14c-10/12-1122', batchNumber: '142-10-7788',
        brand: "Trader Joe's", grade: '10/18', count: '14c', variety: 'H-Less', sampleSize: '14 gms', uniformity: '1:3',
        totalDefects: '14 gms -95%', finalResult: 'Pass', correctiveAction: 'Batch Meets Standards',
        decomposition:        { value: 0.50, pass: true  },
        discoloration:        { value: 0.26, pass: true  },
        softShellLooseShell:  { value: 0.22, pass: false },
        sandVein:             { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        legsShellSwimmerets:  { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.36, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:        { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.26, pass: true  },
        wrongCut:             { value: 0.22, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        chippedTail:          { value: 0.22, pass: false },
        foreignMatter:        { value: 0.32, pass: true  },
        fungusParasites:      { value: 4.80, pass: true  },
        presenceOfMetal:      { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
    ],
    'others': [
      {
        key: '1',
        sampleNumber: '42401', section: 'Peeling & Cutting', batchInfo: '150-12c-08/10-2211', batchNumber: '150-80-2211',
        brand: 'Costco', grade: '08/10', count: '14c', variety: 'EZPL', sampleSize: '14 gms', uniformity: '1:2',
        totalDefects: '14 gms -94%', finalResult: 'Pass', correctiveAction: 'Within Spec Limits',
        decomposition:        { value: 0.45, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        softShellLooseShell:  { value: 0.29, pass: true  },
        sandVein:             { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        legsShellSwimmerets:  { value: 0.22, pass: false },
        passFailSpec:         { value: 0.31, pass: true  },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        wrongCut:             { value: 0.32, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.30, pass: true  },
        fungusParasites:      { value: 4.40, pass: true  },
        presenceOfMetal:      { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2',
        sampleNumber: '42401', section: 'Peeling & Cutting', batchInfo: '150-12c-08/10-2211', batchNumber: '151-70-3322',
        brand: 'Walmart', grade: '08/11', count: '9c', variety: 'FRESH', sampleSize: '9 gms', uniformity: '1:3',
        totalDefects: '9 gms -60%', finalResult: 'Fail', correctiveAction: 'Swimmerets Detected',
        decomposition:        { value: 0.22, pass: false },
        discoloration:        { value: 0.10, pass: false },
        softShellLooseShell:  { value: 0.26, pass: true  },
        sandVein:             { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.11, pass: false },
        legsShellSwimmerets:  { value: 0.12, pass: false },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.36, pass: false },
        hangingMeat:          { value: 0.22, pass: false },
        wrongCut:             { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        fungusParasites:      { value: 5.80, pass: false },
        presenceOfMetal:      { value: 1.90, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3',
        sampleNumber: '42401', section: 'Peeling & Cutting', batchInfo: '150-12c-08/10-2211', batchNumber: '152-60-4433',
        brand: 'Target', grade: '08/12', count: '11c', variety: 'FROZEN', sampleSize: '11 gms', uniformity: '1:1',
        totalDefects: '11 gms -87%', finalResult: 'Pass', correctiveAction: 'Clean Batch',
        decomposition:        { value: 0.47, pass: true  },
        discoloration:        { value: 0.26, pass: true  },
        softShellLooseShell:  { value: 0.22, pass: false },
        sandVein:             { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        legsShellSwimmerets:  { value: 0.22, pass: false },
        passFailSpec:         { value: 0.33, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:        { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        wrongCut:             { value: 0.26, pass: true  },
        brokenTail:           { value: 0.27, pass: true  },
        chippedTail:          { value: 0.22, pass: false },
        foreignMatter:        { value: 0.26, pass: true  },
        fungusParasites:      { value: 4.15, pass: true  },
        presenceOfMetal:      { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4',
        sampleNumber: '42401', section: 'Peeling & Cutting', batchInfo: '150-12c-08/10-2211', batchNumber: '153-50-5544',
        brand: 'Kroger', grade: '08/13', count: '7c', variety: 'FRESH', sampleSize: '7 gms', uniformity: '1:4',
        totalDefects: '7 gms -55%', finalResult: 'Fail', correctiveAction: 'Sand Vein Present',
        decomposition:        { value: 0.22, pass: false },
        discoloration:        { value: 0.14, pass: false },
        softShellLooseShell:  { value: 0.26, pass: true  },
        sandVein:             { value: 0.09, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        legsShellSwimmerets:  { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.39, pass: false },
        hangingMeat:          { value: 0.22, pass: false },
        wrongCut:             { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        fungusParasites:      { value: 3.60, pass: true  },
        presenceOfMetal:      { value: 2.10, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5',
        sampleNumber: '42401', section: 'Peeling & Cutting', batchInfo: '150-12c-08/10-2211', batchNumber: '154-40-6655',
        brand: 'Whole Foods', grade: '08/14', count: '12c', variety: 'EZPL', sampleSize: '12 gms', uniformity: '1:5',
        totalDefects: '12 gms -78%', finalResult: 'Pass', correctiveAction: 'Minimal Defects',
        decomposition:        { value: 0.41, pass: true  },
        discoloration:        { value: 0.22, pass: false },
        softShellLooseShell:  { value: 0.26, pass: true  },
        sandVein:             { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        legsShellSwimmerets:  { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.30, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:        { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.26, pass: true  },
        wrongCut:             { value: 0.22, pass: false },
        brokenTail:           { value: 0.26, pass: true  },
        chippedTail:          { value: 0.22, pass: false },
        foreignMatter:        { value: 0.26, pass: true  },
        fungusParasites:      { value: 4.30, pass: true  },
        presenceOfMetal:      { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6',
        sampleNumber: '42401', section: 'Peeling & Cutting', batchInfo: '150-12c-08/10-2211', batchNumber: '155-30-7766',
        brand: "Sam's Club", grade: '08/15', count: '8c', variety: 'FROZEN', sampleSize: '8 gms', uniformity: '1:2',
        totalDefects: '8 gms -70%', finalResult: 'Fail', correctiveAction: 'Broken Tail Observed',
        decomposition:        { value: 0.22, pass: false },
        discoloration:        { value: 0.08, pass: false },
        softShellLooseShell:  { value: 0.26, pass: true  },
        sandVein:             { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.10, pass: false },
        legsShellSwimmerets:  { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        brokenDamaged:        { value: 0.26, pass: true  },
        hangingMeat:          { value: 0.22, pass: false },
        wrongCut:             { value: 0.26, pass: true  },
        brokenTail:           { value: 0.16, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        fungusParasites:      { value: 3.70, pass: true  },
        presenceOfMetal:      { value: 1.40, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7',
        sampleNumber: '42401', section: 'Peeling & Cutting', batchInfo: '150-12c-08/10-2211', batchNumber: '156-20-8877',
        brand: "Trader Joe's", grade: '08/16', count: '13c', variety: 'EZPL', sampleSize: '13 gms', uniformity: '1:3',
        totalDefects: '13 gms -91%', finalResult: 'Pass', correctiveAction: 'Premium Quality Batch',
        decomposition:        { value: 0.49, pass: true  },
        discoloration:        { value: 0.26, pass: true  },
        softShellLooseShell:  { value: 0.22, pass: false },
        sandVein:             { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        legsShellSwimmerets:  { value: 0.22, pass: false },
        passFailSpec:         { value: 0.35, pass: true  },
        correctiveActionSpec: { value: 0.26, pass: true  },
        brokenDamaged:        { value: 0.22, pass: false },
        hangingMeat:          { value: 0.26, pass: true  },
        wrongCut:             { value: 0.26, pass: true  },
        brokenTail:           { value: 0.22, pass: false },
        chippedTail:          { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.28, pass: true  },
        fungusParasites:      { value: 4.70, pass: true  },
        presenceOfMetal:      { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
    ],
  },
};

export default PeelingCuttingConfig;
