const ReceivingDetailsConfig = {
  baseCols: [
    { key: 'sampleId',      label: 'Sample ID'                          },
    { key: 'section',       label: 'Section'                            },
    { key: 'batchInfo',     label: 'Batch Info'                         },
    { key: 'batchNumber',   label: 'Batch Number'                       },
    { key: 'count',         label: 'Count'                              },
    { key: 'preHarvestId',  label: 'Pre- Harvest ID', type: 'preHarvestId' },
    { key: 'photo',         label: 'Photo',           type: 'photo'     },
    { key: 'prodMetSpec',   label: 'Prod.Met.Spec.',  type: 'passFail'  },
    { key: 'supervisor',    label: 'Supervisor'                         },
    { key: 'remarks',       label: 'Remarks'                            },
  ],
  extraCols: [],
  valueCols: [
    { key: 'dropHead',          label: 'Drop Head (Spec)'          },
    { key: 'decomposition',     label: 'Decomposition (Spec)'      },
    { key: 'dehydration',       label: 'Dehydration (Spec)'        },
    { key: 'softShell',         label: 'Soft Shell (Spec)'         },
    { key: 'looseShell',        label: 'Loose Shell (Spec)'        },
    { key: 'blackTail',         label: 'Black Tail (Spec)'         },
    { key: 'blackSpots',        label: 'Black Spots (Spec)'        },
    { key: 'passFailSpec',      label: 'Pass/Fail (Spec)'          },
    { key: 'correctiveActionSpec', label: 'Corrective Action (Spec)' },
    { key: 'muddySmell',        label: 'Muddy Smell (Spec)'        },
    { key: 'broken',            label: 'Broken (Spec)'             },
    { key: 'foreignMatter',     label: 'Foreign Matter (Spec)'     },
    { key: 'pestInfestation',   label: 'Pest Infestation (Spec)'   },
    { key: 'wssv',              label: 'WSSV (Spec)'               },
    { key: 'fungusParasites',   label: 'Fungus/Parasites (Spec)'   },
  ],
  actionLabel: 'Action',
  data: {
    'pre-harvest': [
      {
        key: '1', sampleId: '42352', section: 'Receiving', batchInfo: '125-12c-3215',
        batchNumber: '42352', count: '09c',
        preHarvestId: { id: 'Ap0345135/001PH', verified: true },
        prodMetSpec: 'Pass', supervisor: 'Rahul', remarks: 'Shrimp has Dark Spots',
        dropHead:             { value: 0.49, pass: true  },
        decomposition:        { value: 0.10, pass: false },
        dehydration:          { value: 0.34, pass: true  },
        softShell:            { value: 0.34, pass: true  },
        looseShell:           { value: 0.34, pass: true  },
        blackTail:            { value: 0.10, pass: false },
        blackSpots:           { value: 0.10, pass: false },
        passFailSpec:         { value: 0.10, pass: false },
        correctiveActionSpec: { value: 0.10, pass: false },
        muddySmell:           { value: 0.34, pass: true  },
        broken:               { value: 0.28, pass: false },
        foreignMatter:        { value: 0.34, pass: true  },
        pestInfestation:      { value: 0.34, pass: true  },
        wssv:                 { value: 0.33, pass: true  },
        fungusParasites:      { value: 0.34, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', sampleId: '42353', section: 'Receiving', batchInfo: '125-12c-3215',
        batchNumber: '42353', count: '09c',
        preHarvestId: { id: 'Ap0345136/002PH', verified: true },
        prodMetSpec: 'Pass', supervisor: 'Maya', remarks: 'Fish is Discolored',
        dropHead:             { value: 0.26, pass: true  },
        decomposition:        { value: 0.22, pass: false },
        dehydration:          { value: 0.26, pass: true  },
        softShell:            { value: 0.22, pass: false },
        looseShell:           { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        muddySmell:           { value: 0.22, pass: false },
        broken:               { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        pestInfestation:      { value: 0.26, pass: true  },
        wssv:                 { value: 0.22, pass: false },
        fungusParasites:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '3', sampleId: '42354', section: 'Receiving', batchInfo: '125-12c-3215',
        batchNumber: '42354', count: '09c',
        preHarvestId: { id: 'Ap0345137/003PH', verified: true },
        prodMetSpec: 'Pass', supervisor: 'Oliver', remarks: 'Meat is Expired',
        dropHead:             { value: 0.22, pass: false },
        decomposition:        { value: 0.26, pass: true  },
        dehydration:          { value: 0.22, pass: false },
        softShell:            { value: 0.26, pass: true  },
        looseShell:           { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        muddySmell:           { value: 0.26, pass: true  },
        broken:               { value: 0.35, pass: false },
        foreignMatter:        { value: 0.26, pass: true  },
        pestInfestation:      { value: 0.22, pass: false },
        wssv:                 { value: 0.26, pass: true  },
        fungusParasites:      { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4', sampleId: '42355', section: 'Receiving', batchInfo: '125-12c-3215',
        batchNumber: '42355', count: '09c',
        preHarvestId: { id: 'Ap0345138/004PH', verified: true },
        prodMetSpec: 'Fail', supervisor: 'Sophie', remarks: 'Vegetables are Wilted',
        dropHead:             { value: 0.26, pass: true  },
        decomposition:        { value: 0.22, pass: false },
        dehydration:          { value: 0.26, pass: true  },
        softShell:            { value: 0.22, pass: false },
        looseShell:           { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        muddySmell:           { value: 0.22, pass: false },
        broken:               { value: 0.30, pass: false },
        foreignMatter:        { value: 0.26, pass: true  },
        pestInfestation:      { value: 0.22, pass: false },
        wssv:                 { value: 0.26, pass: true  },
        fungusParasites:      { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5', sampleId: '42356', section: 'Receiving', batchInfo: '125-12c-3215',
        batchNumber: '42356', count: '09c',
        preHarvestId: { id: 'Ap0345139/005PH', verified: false },
        prodMetSpec: 'Pass', supervisor: 'Liam', remarks: 'Dairy Products arrived',
        dropHead:             { value: 0.22, pass: false },
        decomposition:        { value: 0.26, pass: true  },
        dehydration:          { value: 0.22, pass: false },
        softShell:            { value: 0.26, pass: true  },
        looseShell:           { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        muddySmell:           { value: 0.26, pass: true  },
        broken:               { value: 0.22, pass: false },
        foreignMatter:        { value: 0.26, pass: true  },
        pestInfestation:      { value: 0.22, pass: false },
        wssv:                 { value: 0.26, pass: true  },
        fungusParasites:      { value: 0.22, pass: false },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6', sampleId: '42357', section: 'Receiving', batchInfo: '125-12c-3215',
        batchNumber: '42357', count: '09c',
        preHarvestId: { id: 'Ap0345140/006PH', verified: true },
        prodMetSpec: 'Fail', supervisor: 'Emma', remarks: 'Canned Goods arrived',
        dropHead:             { value: 0.26, pass: true  },
        decomposition:        { value: 0.22, pass: false },
        dehydration:          { value: 0.26, pass: true  },
        softShell:            { value: 0.22, pass: false },
        looseShell:           { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        muddySmell:           { value: 0.22, pass: false },
        broken:               { value: 0.38, pass: false },
        foreignMatter:        { value: 0.26, pass: true  },
        pestInfestation:      { value: 0.22, pass: false },
        wssv:                 { value: 0.26, pass: true  },
        fungusParasites:      { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7', sampleId: '42358', section: 'Receiving', batchInfo: '125-12c-3215',
        batchNumber: '42358', count: '09c',
        preHarvestId: { id: 'Ap0345141/007PH', verified: true },
        prodMetSpec: 'Pass', supervisor: 'Noah', remarks: 'Frozen batch intact',
        dropHead:             { value: 0.48, pass: true  },
        decomposition:        { value: 0.22, pass: false },
        dehydration:          { value: 0.26, pass: true  },
        softShell:            { value: 0.22, pass: false },
        looseShell:           { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        muddySmell:           { value: 0.22, pass: false },
        broken:               { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        pestInfestation:      { value: 0.26, pass: true  },
        wssv:                 { value: 0.22, pass: false },
        fungusParasites:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
    ],
    'processing': [
      {
        key: '1', sampleId: '42360', section: 'Receiving', batchInfo: '136-12c-3216',
        batchNumber: '42360', count: '09c',
        preHarvestId: { id: 'Bp0346135/001PH', verified: true },
        prodMetSpec: 'Pass', supervisor: 'Rahul', remarks: 'Processing batch clear',
        dropHead:             { value: 0.44, pass: true  },
        decomposition:        { value: 0.22, pass: false },
        dehydration:          { value: 0.26, pass: true  },
        softShell:            { value: 0.22, pass: false },
        looseShell:           { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        muddySmell:           { value: 0.22, pass: false },
        broken:               { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        pestInfestation:      { value: 0.26, pass: true  },
        wssv:                 { value: 0.22, pass: false },
        fungusParasites:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', sampleId: '42361', section: 'Receiving', batchInfo: '136-12c-3216',
        batchNumber: '42361', count: '09c',
        preHarvestId: { id: 'Bp0346136/002PH', verified: false },
        prodMetSpec: 'Fail', supervisor: 'Maya', remarks: 'Decomposition found',
        dropHead:             { value: 0.22, pass: false },
        decomposition:        { value: 0.09, pass: false },
        dehydration:          { value: 0.26, pass: true  },
        softShell:            { value: 0.22, pass: false },
        looseShell:           { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        muddySmell:           { value: 0.22, pass: false },
        broken:               { value: 0.31, pass: false },
        foreignMatter:        { value: 0.26, pass: true  },
        pestInfestation:      { value: 0.22, pass: false },
        wssv:                 { value: 0.26, pass: true  },
        fungusParasites:      { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3', sampleId: '42362', section: 'Receiving', batchInfo: '136-12c-3216',
        batchNumber: '42362', count: '09c',
        preHarvestId: { id: 'Bp0346137/003PH', verified: true },
        prodMetSpec: 'Pass', supervisor: 'Oliver', remarks: 'Good batch quality',
        dropHead:             { value: 0.46, pass: true  },
        decomposition:        { value: 0.22, pass: false },
        dehydration:          { value: 0.26, pass: true  },
        softShell:            { value: 0.22, pass: false },
        looseShell:           { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        muddySmell:           { value: 0.22, pass: false },
        broken:               { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        pestInfestation:      { value: 0.26, pass: true  },
        wssv:                 { value: 0.22, pass: false },
        fungusParasites:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4', sampleId: '42363', section: 'Receiving', batchInfo: '136-12c-3216',
        batchNumber: '42363', count: '09c',
        preHarvestId: { id: 'Bp0346138/004PH', verified: true },
        prodMetSpec: 'Fail', supervisor: 'Sophie', remarks: 'Pest detected',
        dropHead:             { value: 0.22, pass: false },
        decomposition:        { value: 0.26, pass: true  },
        dehydration:          { value: 0.22, pass: false },
        softShell:            { value: 0.26, pass: true  },
        looseShell:           { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        muddySmell:           { value: 0.26, pass: true  },
        broken:               { value: 0.33, pass: false },
        foreignMatter:        { value: 0.26, pass: true  },
        pestInfestation:      { value: 0.08, pass: false },
        wssv:                 { value: 0.26, pass: true  },
        fungusParasites:      { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5', sampleId: '42364', section: 'Receiving', batchInfo: '136-12c-3216',
        batchNumber: '42364', count: '09c',
        preHarvestId: { id: 'Bp0346139/005PH', verified: true },
        prodMetSpec: 'Pass', supervisor: 'Liam', remarks: 'Clean receive',
        dropHead:             { value: 0.43, pass: true  },
        decomposition:        { value: 0.22, pass: false },
        dehydration:          { value: 0.26, pass: true  },
        softShell:            { value: 0.22, pass: false },
        looseShell:           { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        muddySmell:           { value: 0.22, pass: false },
        broken:               { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        pestInfestation:      { value: 0.26, pass: true  },
        wssv:                 { value: 0.22, pass: false },
        fungusParasites:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6', sampleId: '42365', section: 'Receiving', batchInfo: '136-12c-3216',
        batchNumber: '42365', count: '09c',
        preHarvestId: { id: 'Bp0346140/006PH', verified: false },
        prodMetSpec: 'Fail', supervisor: 'Emma', remarks: 'WSSV risk flagged',
        dropHead:             { value: 0.22, pass: false },
        decomposition:        { value: 0.26, pass: true  },
        dehydration:          { value: 0.22, pass: false },
        softShell:            { value: 0.26, pass: true  },
        looseShell:           { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        muddySmell:           { value: 0.26, pass: true  },
        broken:               { value: 0.22, pass: false },
        foreignMatter:        { value: 0.26, pass: true  },
        pestInfestation:      { value: 0.22, pass: false },
        wssv:                 { value: 0.08, pass: false },
        fungusParasites:      { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7', sampleId: '42366', section: 'Receiving', batchInfo: '136-12c-3216',
        batchNumber: '42366', count: '09c',
        preHarvestId: { id: 'Bp0346141/007PH', verified: true },
        prodMetSpec: 'Pass', supervisor: 'Noah', remarks: 'Premium batch',
        dropHead:             { value: 0.50, pass: true  },
        decomposition:        { value: 0.22, pass: false },
        dehydration:          { value: 0.26, pass: true  },
        softShell:            { value: 0.22, pass: false },
        looseShell:           { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        muddySmell:           { value: 0.22, pass: false },
        broken:               { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        pestInfestation:      { value: 0.26, pass: true  },
        wssv:                 { value: 0.22, pass: false },
        fungusParasites:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
    ],
    'others': [
      {
        key: '1', sampleId: '42370', section: 'Receiving', batchInfo: '150-12c-3217',
        batchNumber: '42370', count: '09c',
        preHarvestId: { id: 'Cp0347135/001PH', verified: true },
        prodMetSpec: 'Pass', supervisor: 'Rahul', remarks: 'Within spec limits',
        dropHead:             { value: 0.45, pass: true  },
        decomposition:        { value: 0.22, pass: false },
        dehydration:          { value: 0.26, pass: true  },
        softShell:            { value: 0.22, pass: false },
        looseShell:           { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        muddySmell:           { value: 0.22, pass: false },
        broken:               { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        pestInfestation:      { value: 0.26, pass: true  },
        wssv:                 { value: 0.22, pass: false },
        fungusParasites:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', sampleId: '42371', section: 'Receiving', batchInfo: '150-12c-3217',
        batchNumber: '42371', count: '09c',
        preHarvestId: { id: 'Cp0347136/002PH', verified: false },
        prodMetSpec: 'Fail', supervisor: 'Maya', remarks: 'Fungus detected',
        dropHead:             { value: 0.22, pass: false },
        decomposition:        { value: 0.26, pass: true  },
        dehydration:          { value: 0.22, pass: false },
        softShell:            { value: 0.26, pass: true  },
        looseShell:           { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        muddySmell:           { value: 0.26, pass: true  },
        broken:               { value: 0.36, pass: false },
        foreignMatter:        { value: 0.26, pass: true  },
        pestInfestation:      { value: 0.22, pass: false },
        wssv:                 { value: 0.26, pass: true  },
        fungusParasites:      { value: 0.08, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3', sampleId: '42372', section: 'Receiving', batchInfo: '150-12c-3217',
        batchNumber: '42372', count: '09c',
        preHarvestId: { id: 'Cp0347137/003PH', verified: true },
        prodMetSpec: 'Pass', supervisor: 'Oliver', remarks: 'Clean batch',
        dropHead:             { value: 0.47, pass: true  },
        decomposition:        { value: 0.22, pass: false },
        dehydration:          { value: 0.26, pass: true  },
        softShell:            { value: 0.22, pass: false },
        looseShell:           { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        muddySmell:           { value: 0.22, pass: false },
        broken:               { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        pestInfestation:      { value: 0.26, pass: true  },
        wssv:                 { value: 0.22, pass: false },
        fungusParasites:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4', sampleId: '42373', section: 'Receiving', batchInfo: '150-12c-3217',
        batchNumber: '42373', count: '09c',
        preHarvestId: { id: 'Cp0347138/004PH', verified: true },
        prodMetSpec: 'Fail', supervisor: 'Sophie', remarks: 'Loose shell on arrival',
        dropHead:             { value: 0.22, pass: false },
        decomposition:        { value: 0.26, pass: true  },
        dehydration:          { value: 0.22, pass: false },
        softShell:            { value: 0.26, pass: true  },
        looseShell:           { value: 0.08, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        muddySmell:           { value: 0.26, pass: true  },
        broken:               { value: 0.32, pass: false },
        foreignMatter:        { value: 0.26, pass: true  },
        pestInfestation:      { value: 0.22, pass: false },
        wssv:                 { value: 0.26, pass: true  },
        fungusParasites:      { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5', sampleId: '42374', section: 'Receiving', batchInfo: '150-12c-3217',
        batchNumber: '42374', count: '09c',
        preHarvestId: { id: 'Cp0347139/005PH', verified: true },
        prodMetSpec: 'Pass', supervisor: 'Liam', remarks: 'Minimal defects',
        dropHead:             { value: 0.41, pass: true  },
        decomposition:        { value: 0.22, pass: false },
        dehydration:          { value: 0.26, pass: true  },
        softShell:            { value: 0.22, pass: false },
        looseShell:           { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        muddySmell:           { value: 0.22, pass: false },
        broken:               { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        pestInfestation:      { value: 0.26, pass: true  },
        wssv:                 { value: 0.22, pass: false },
        fungusParasites:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6', sampleId: '42375', section: 'Receiving', batchInfo: '150-12c-3217',
        batchNumber: '42375', count: '09c',
        preHarvestId: { id: 'Cp0347140/006PH', verified: false },
        prodMetSpec: 'Fail', supervisor: 'Emma', remarks: 'Foreign matter found',
        dropHead:             { value: 0.22, pass: false },
        decomposition:        { value: 0.26, pass: true  },
        dehydration:          { value: 0.22, pass: false },
        softShell:            { value: 0.26, pass: true  },
        looseShell:           { value: 0.22, pass: false },
        blackTail:            { value: 0.26, pass: true  },
        blackSpots:           { value: 0.22, pass: false },
        passFailSpec:         { value: 0.26, pass: true  },
        correctiveActionSpec: { value: 0.22, pass: false },
        muddySmell:           { value: 0.26, pass: true  },
        broken:               { value: 0.22, pass: false },
        foreignMatter:        { value: 0.09, pass: false },
        pestInfestation:      { value: 0.26, pass: true  },
        wssv:                 { value: 0.22, pass: false },
        fungusParasites:      { value: 0.26, pass: true  },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7', sampleId: '42376', section: 'Receiving', batchInfo: '150-12c-3217',
        batchNumber: '42376', count: '09c',
        preHarvestId: { id: 'Cp0347141/007PH', verified: true },
        prodMetSpec: 'Pass', supervisor: 'Noah', remarks: 'Premium quality received',
        dropHead:             { value: 0.52, pass: true  },
        decomposition:        { value: 0.22, pass: false },
        dehydration:          { value: 0.26, pass: true  },
        softShell:            { value: 0.22, pass: false },
        looseShell:           { value: 0.26, pass: true  },
        blackTail:            { value: 0.22, pass: false },
        blackSpots:           { value: 0.26, pass: true  },
        passFailSpec:         { value: 0.22, pass: false },
        correctiveActionSpec: { value: 0.26, pass: true  },
        muddySmell:           { value: 0.22, pass: false },
        broken:               { value: 0.26, pass: true  },
        foreignMatter:        { value: 0.22, pass: false },
        pestInfestation:      { value: 0.26, pass: true  },
        wssv:                 { value: 0.22, pass: false },
        fungusParasites:      { value: 0.26, pass: true  },
        status: 'Pass', action: 'Approved',
      },
    ],
  },
};

export default ReceivingDetailsConfig;
