const SoakingConfig = {
  hideParams: true,
  baseCols: [
    { key: 'sampleNumber',   label: 'Sample Number'   },
    { key: 'section',        label: 'Section'         },
    { key: 'batchInfo',      label: 'Batch Info'      },
    { key: 'batchNumber',    label: 'Batch Number'    },
    { key: 'brand',          label: 'Brand'           },
    { key: 'grade',          label: 'Grade'           },
    { key: 'variety',        label: 'Variety'         },
    { key: 'tank',           label: 'Tank'            },
    { key: 'additives',      label: 'Additives'       },
    { key: 'soakInTime',     label: 'Soak In Time'    },
    { key: 'soakInCount',    label: 'Soak In Count'   },
    { key: 'soakOutTime',    label: 'Soak Out Time'   },
    { key: 'soakOutCount',   label: 'Soak Out Count'  },
    { key: 'soakingDuration',label: 'Soaking Duration'},
    { key: 'oversoaked',     label: 'Oversoaked'      },
    { key: 'remarks',        label: 'Remarks'         },
    { key: 'issuedTo',       label: 'Issued to'       },
  ],
  extraCols: [],
  valueCols: [
    { key: 'dehydration',   label: 'Dehydration'        },
    { key: 'discoloration', label: 'Discoloration'      },
    { key: 'damaged',       label: 'Damaged/Broken'     },
    { key: 'sandVeins',     label: 'Sand Veins Present' },
    { key: 'blackspot',     label: 'Blackspot'          },
  ],
  actionLabel: 'Action',
  data: {
    'pre-harvest': [
      {
        key: '1', sampleNumber: '42213', section: 'Soaking', batchInfo: '125-13c-12/14-3214',
        batchNumber: '125-65-3214', brand: 'Walmart', grade: '12/14', variety: 'EZPL',
        tank: '3', additives: '1:2', soakInTime: '06:00:24', soakInCount: '12 c',
        soakOutTime: '06:00:24', soakOutCount: '12 c', soakingDuration: '12:00:48',
        oversoaked: 'Yes', remarks: 'Shrimp has Dark Spots', issuedTo: 'Cooked',
        dehydration: { value: 0.26, pass: true  }, discoloration: null,
        damaged: null, sandVeins: null, blackspot: { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '2', sampleNumber: '42213', section: 'Soaking', batchInfo: '125-13c-12/14-3214',
        batchNumber: '234-76-8120', brand: 'Target', grade: '01/15', variety: 'RNDM',
        tank: '5', additives: '2:1', soakInTime: '08:15:30', soakInCount: '8 c',
        soakOutTime: '08:15:30', soakOutCount: '8 c', soakingDuration: '15:30:45',
        oversoaked: 'No', remarks: 'Chicken is Tender', issuedTo: 'Raw',
        dehydration: null, discoloration: { value: 0.26, pass: true },
        damaged: null, sandVeins: { value: 0.30, pass: true }, blackspot: null,
        status: 'Pass', action: 'Approved',
      },
      {
        key: '3', sampleNumber: '42213', section: 'Soaking', batchInfo: '125-13c-12/14-3214',
        batchNumber: '345-89-6321', brand: 'Kroger', grade: '02/20', variety: 'FRESH',
        tank: '2', additives: '1:4', soakInTime: '09:45:12', soakInCount: '10 c',
        soakOutTime: '09:45:12', soakOutCount: '10 c', soakingDuration: '17:15:24',
        oversoaked: 'Yes', remarks: 'Vegetables are Wilted', issuedTo: 'Cooked',
        dehydration: null, discoloration: { value: 0.22, pass: false },
        damaged: { value: 0.26, pass: true }, sandVeins: null, blackspot: null,
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '4', sampleNumber: '42213', section: 'Soaking', batchInfo: '125-13c-12/14-3214',
        batchNumber: '456-23-9841', brand: 'Costco', grade: '11/30', variety: 'COLDD',
        tank: '4', additives: '3:2', soakInTime: '10:00:00', soakInCount: '5 c',
        soakOutTime: '10:00:00', soakOutCount: '5 c', soakingDuration: '20:00:00',
        oversoaked: 'No', remarks: 'Dessert is Firm', issuedTo: 'Chilled',
        dehydration: { value: 0.28, pass: true }, discoloration: null,
        damaged: null, sandVeins: null, blackspot: { value: 0.26, pass: true },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '5', sampleNumber: '42213', section: 'Soaking', batchInfo: '125-13c-12/14-3214',
        batchNumber: '567-45-1234', brand: 'Whole Foods', grade: '03/25', variety: 'GRLLD',
        tank: '6', additives: '1:1', soakInTime: '12:30:15', soakInCount: '15 c',
        soakOutTime: '12:30:15', soakOutCount: '15 c', soakingDuration: '18:45:30',
        oversoaked: 'Yes', remarks: 'Steak is Juicy', issuedTo: 'Cooked',
        dehydration: null, discoloration: { value: 0.26, pass: true },
        damaged: { value: 0.22, pass: false }, sandVeins: { value: 0.26, pass: true }, blackspot: null,
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '6', sampleNumber: '42213', section: 'Soaking', batchInfo: '125-13c-12/14-3214',
        batchNumber: '678-90-5432', brand: 'Aldi', grade: '04/05', variety: 'FROZN',
        tank: '8', additives: '1:3', soakInTime: '11:15:55', soakInCount: '20 c',
        soakOutTime: '11:15:55', soakOutCount: '20 c', soakingDuration: '19:30:00',
        oversoaked: 'No', remarks: 'Fish is Solid', issuedTo: 'Frozen',
        dehydration: { value: 0.26, pass: true }, discoloration: null,
        damaged: null, sandVeins: { value: 0.26, pass: true }, blackspot: null,
        status: 'Pass', action: 'Approved',
      },
      {
        key: '7', sampleNumber: '42213', section: 'Soaking', batchInfo: '125-13c-12/14-3214',
        batchNumber: '789-34-6543', brand: "Trader Joe's", grade: '05/10', variety: 'SMKD',
        tank: '7', additives: '2:3', soakInTime: '13:00:00', soakInCount: '18 c',
        soakOutTime: '13:00:00', soakOutCount: '18 c', soakingDuration: '21:00:00',
        oversoaked: 'Yes', remarks: 'Meat is Expired', issuedTo: 'Frozen',
        dehydration: null, discoloration: { value: 0.24, pass: false },
        damaged: null, sandVeins: null, blackspot: { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
    ],
    'processing': [
      {
        key: '1', sampleNumber: '42214', section: 'Soaking', batchInfo: '136-13c-12/14-3215',
        batchNumber: '125-66-3215', brand: 'Costco', grade: '12/14', variety: 'H-Less',
        tank: '1', additives: '1:2', soakInTime: '07:00:00', soakInCount: '14 c',
        soakOutTime: '07:00:00', soakOutCount: '14 c', soakingDuration: '13:00:00',
        oversoaked: 'No', remarks: 'Clean batch', issuedTo: 'Cooked',
        dehydration: null, discoloration: { value: 0.26, pass: true },
        damaged: null, sandVeins: { value: 0.28, pass: true }, blackspot: null,
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', sampleNumber: '42214', section: 'Soaking', batchInfo: '136-13c-12/14-3215',
        batchNumber: '236-77-8121', brand: 'Walmart', grade: '10/12', variety: 'H-ON',
        tank: '4', additives: '2:1', soakInTime: '09:30:00', soakInCount: '9 c',
        soakOutTime: '09:30:00', soakOutCount: '9 c', soakingDuration: '16:00:00',
        oversoaked: 'Yes', remarks: 'Loose shell detected', issuedTo: 'Raw',
        dehydration: { value: 0.22, pass: false }, discoloration: null,
        damaged: { value: 0.22, pass: false }, sandVeins: null, blackspot: null,
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3', sampleNumber: '42214', section: 'Soaking', batchInfo: '136-13c-12/14-3215',
        batchNumber: '346-88-6322', brand: 'Target', grade: '08/10', variety: 'H-Less',
        tank: '3', additives: '1:4', soakInTime: '10:45:00', soakInCount: '11 c',
        soakOutTime: '10:45:00', soakOutCount: '11 c', soakingDuration: '18:00:00',
        oversoaked: 'No', remarks: 'Good batch quality', issuedTo: 'Cooked',
        dehydration: { value: 0.26, pass: true }, discoloration: { value: 0.26, pass: true },
        damaged: null, sandVeins: null, blackspot: { value: 0.26, pass: true },
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4', sampleNumber: '42214', section: 'Soaking', batchInfo: '136-13c-12/14-3215',
        batchNumber: '457-24-9842', brand: 'Kroger', grade: '14/16', variety: 'H-ON',
        tank: '6', additives: '3:2', soakInTime: '11:00:00', soakInCount: '6 c',
        soakOutTime: '11:00:00', soakOutCount: '6 c', soakingDuration: '21:00:00',
        oversoaked: 'Yes', remarks: 'Discoloration noted', issuedTo: 'Chilled',
        dehydration: null, discoloration: { value: 0.24, pass: false },
        damaged: null, sandVeins: { value: 0.22, pass: false }, blackspot: null,
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5', sampleNumber: '42214', section: 'Soaking', batchInfo: '136-13c-12/14-3215',
        batchNumber: '568-46-1235', brand: 'Whole Foods', grade: '06/08', variety: 'H-Less',
        tank: '5', additives: '1:1', soakInTime: '13:00:00', soakInCount: '16 c',
        soakOutTime: '13:00:00', soakOutCount: '16 c', soakingDuration: '19:30:00',
        oversoaked: 'No', remarks: 'Minimal defects', issuedTo: 'Cooked',
        dehydration: { value: 0.30, pass: true }, discoloration: { value: 0.26, pass: true },
        damaged: null, sandVeins: { value: 0.26, pass: true }, blackspot: null,
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6', sampleNumber: '42214', section: 'Soaking', batchInfo: '136-13c-12/14-3215',
        batchNumber: '679-91-5433', brand: "Sam's Club", grade: '16/18', variety: 'H-ON',
        tank: '2', additives: '1:3', soakInTime: '12:15:00', soakInCount: '22 c',
        soakOutTime: '12:15:00', soakOutCount: '22 c', soakingDuration: '20:30:00',
        oversoaked: 'Yes', remarks: 'Sand veins present', issuedTo: 'Frozen',
        dehydration: null, discoloration: null,
        damaged: { value: 0.22, pass: false }, sandVeins: null, blackspot: { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7', sampleNumber: '42214', section: 'Soaking', batchInfo: '136-13c-12/14-3215',
        batchNumber: '790-35-6544', brand: "Trader Joe's", grade: '21/25', variety: 'H-Less',
        tank: '9', additives: '2:3', soakInTime: '14:00:00', soakInCount: '19 c',
        soakOutTime: '14:00:00', soakOutCount: '19 c', soakingDuration: '22:00:00',
        oversoaked: 'No', remarks: 'Premium batch', issuedTo: 'Cooked',
        dehydration: { value: 0.26, pass: true }, discoloration: { value: 0.28, pass: true },
        damaged: null, sandVeins: { value: 0.26, pass: true }, blackspot: null,
        status: 'Pass', action: 'Approved',
      },
    ],
    'others': [
      {
        key: '1', sampleNumber: '42215', section: 'Soaking', batchInfo: '150-13c-12/14-3216',
        batchNumber: '125-67-3216', brand: 'Costco', grade: '12/14', variety: 'EZPL',
        tank: '1', additives: '1:2', soakInTime: '07:30:00', soakInCount: '13 c',
        soakOutTime: '07:30:00', soakOutCount: '13 c', soakingDuration: '13:30:00',
        oversoaked: 'No', remarks: 'Within spec limits', issuedTo: 'Cooked',
        dehydration: { value: 0.26, pass: true }, discoloration: null,
        damaged: null, sandVeins: null, blackspot: { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '2', sampleNumber: '42215', section: 'Soaking', batchInfo: '150-13c-12/14-3216',
        batchNumber: '237-78-8122', brand: 'Walmart', grade: '10/12', variety: 'FRESH',
        tank: '3', additives: '2:1', soakInTime: '09:00:00', soakInCount: '10 c',
        soakOutTime: '09:00:00', soakOutCount: '10 c', soakingDuration: '16:30:00',
        oversoaked: 'Yes', remarks: 'Fungus detected', issuedTo: 'Raw',
        dehydration: null, discoloration: { value: 0.26, pass: true },
        damaged: null, sandVeins: { value: 0.26, pass: true }, blackspot: null,
        status: 'Pass', action: 'Approved',
      },
      {
        key: '3', sampleNumber: '42215', section: 'Soaking', batchInfo: '150-13c-12/14-3216',
        batchNumber: '347-89-6323', brand: 'Target', grade: '08/10', variety: 'FROZEN',
        tank: '5', additives: '1:4', soakInTime: '10:00:00', soakInCount: '11 c',
        soakOutTime: '10:00:00', soakOutCount: '11 c', soakingDuration: '17:30:00',
        oversoaked: 'No', remarks: 'Clean batch', issuedTo: 'Cooked',
        dehydration: null, discoloration: { value: 0.22, pass: false },
        damaged: { value: 0.22, pass: false }, sandVeins: null, blackspot: null,
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '4', sampleNumber: '42215', section: 'Soaking', batchInfo: '150-13c-12/14-3216',
        batchNumber: '458-25-9843', brand: 'Kroger', grade: '14/16', variety: 'FRESH',
        tank: '7', additives: '3:2', soakInTime: '11:30:00', soakInCount: '7 c',
        soakOutTime: '11:30:00', soakOutCount: '7 c', soakingDuration: '20:30:00',
        oversoaked: 'Yes', remarks: 'Loose shell on arrival', issuedTo: 'Chilled',
        dehydration: { value: 0.28, pass: true }, discoloration: { value: 0.26, pass: true },
        damaged: null, sandVeins: { value: 0.26, pass: true }, blackspot: null,
        status: 'Pass', action: 'Approved',
      },
      {
        key: '5', sampleNumber: '42215', section: 'Soaking', batchInfo: '150-13c-12/14-3216',
        batchNumber: '569-47-1236', brand: 'Whole Foods', grade: '06/08', variety: 'EZPL',
        tank: '2', additives: '1:1', soakInTime: '13:30:00', soakInCount: '17 c',
        soakOutTime: '13:30:00', soakOutCount: '17 c', soakingDuration: '18:30:00',
        oversoaked: 'No', remarks: 'Minimal defects', issuedTo: 'Cooked',
        dehydration: null, discoloration: null,
        damaged: { value: 0.22, pass: false }, sandVeins: null, blackspot: { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '6', sampleNumber: '42215', section: 'Soaking', batchInfo: '150-13c-12/14-3216',
        batchNumber: '680-92-5434', brand: "Sam's Club", grade: '16/18', variety: 'FROZEN',
        tank: '4', additives: '1:3', soakInTime: '12:45:00', soakInCount: '23 c',
        soakOutTime: '12:45:00', soakOutCount: '23 c', soakingDuration: '21:30:00',
        oversoaked: 'Yes', remarks: 'Foreign matter found', issuedTo: 'Frozen',
        dehydration: { value: 0.26, pass: true }, discoloration: { value: 0.26, pass: true },
        damaged: null, sandVeins: null, blackspot: null,
        status: 'Pass', action: 'Approved',
      },
      {
        key: '7', sampleNumber: '42215', section: 'Soaking', batchInfo: '150-13c-12/14-3216',
        batchNumber: '791-36-6545', brand: "Trader Joe's", grade: '21/25', variety: 'EZPL',
        tank: '10', additives: '2:3', soakInTime: '14:30:00', soakInCount: '20 c',
        soakOutTime: '14:30:00', soakOutCount: '20 c', soakingDuration: '22:30:00',
        oversoaked: 'No', remarks: 'Premium quality received', issuedTo: 'Frozen',
        dehydration: null, discoloration: { value: 0.22, pass: false },
        damaged: null, sandVeins: null, blackspot: { value: 0.22, pass: false },
        status: 'Fail', action: 'Rejected',
      },
    ],
  },
};

export default SoakingConfig;
