const F = (value, pass) => ({ value, pass, unit: '°F' });

const TemperatureConfig = {
  baseCols: [
    { key: 'sampleNumber',          label: 'Sample Number'                    },
    { key: 'section',               label: 'Section'                          },
    { key: 'batchInfo',             label: 'Batch Info'                       },
    { key: 'batchNumber',           label: 'Batch Number'                     },
    { key: 'grade',                 label: 'Grade'                            },
    { key: 'variety',               label: 'Variety'                          },
    { key: 'brand',                 label: 'Brand'                            },
    { key: 'packingStyle',          label: 'Packing Style'                    },
    { key: 'freezer',               label: 'Freezer'                          },
    { key: 'avgProductCoreTemp',    label: 'Average Product Core Temperature' },
    { key: 'counterCoolerWaterTemp',label: 'Counter Cooler Water Temp'        },
    { key: 'coreTempAfterChiller',  label: 'Core Temp of Product after Chiller' },
    { key: 'photo',                 label: 'Photo', type: 'photo'             },
    { key: 'supervisor',            label: 'Supervisor'                       },
    { key: 'remarks',               label: 'Remarks'                          },
  ],
  extraCols: [],
  valueCols: [
    { key: 'productCoreTemp1', label: 'Product Core Temp-1' },
    { key: 'productCoreTemp2', label: 'Product Core Temp-2' },
    { key: 'productCoreTemp3', label: 'Product Core Temp-3' },
    { key: 'productCoreTemp4', label: 'Product Core Temp-4' },
    { key: 'productCoreTemp5', label: 'Product Core Temp-5' },
  ],
  actionLabel: 'Action',
  data: {
    'pre-harvest': [
      {
        key: '1', sampleNumber: '42213', section: 'Temperature', batchInfo: '125-13c-12/14-3214',
        batchNumber: '2026-048264', grade: '12/14', variety: 'EZPL', brand: 'Costco',
        packingStyle: '6*5 Lbs', freezer: 'IQF -4', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '1°C', coreTempAfterChiller: '2°C',
        supervisor: 'Rahul', remarks: 'Shrimp has Dark Spots',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(115, false),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(45,  false),
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', sampleNumber: '42213', section: 'Temperature', batchInfo: '125-13c-12/14-3214',
        batchNumber: '2026-048265', grade: '12/15', variety: 'PD', brand: 'Walmart',
        packingStyle: '10 Lbs', freezer: 'IQF -1', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '2°C', coreTempAfterChiller: '3°C',
        supervisor: 'Maya', remarks: 'Fresh Fish Available',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(115, false),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(120, true),
        status: 'Pass', action: 'Approved',
      },
      {
        key: '3', sampleNumber: '42213', section: 'Temperature', batchInfo: '125-13c-12/14-3214',
        batchNumber: '2026-048266', grade: '12/16', variety: 'H-On', brand: 'Target',
        packingStyle: '8 Lbs', freezer: 'IQF -2', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '4°C', coreTempAfterChiller: '1°C',
        supervisor: 'Jake', remarks: 'Wild Caught Shrimp',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(50,  false),
        productCoreTemp5: F(120, true),
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4', sampleNumber: '42213', section: 'Temperature', batchInfo: '125-13c-12/14-3214',
        batchNumber: '2026-048267', grade: '12/17', variety: 'H-Less', brand: 'Kroger',
        packingStyle: '15 Lbs', freezer: 'IQF -4', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '5°C', coreTempAfterChiller: '5°C',
        supervisor: 'Sara', remarks: 'Tuna Fillet',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(120, true),
        status: 'Pass', action: 'Approved',
      },
      {
        key: '5', sampleNumber: '42213', section: 'Temperature', batchInfo: '125-13c-12/14-3214',
        batchNumber: '2026-048268', grade: '12/18', variety: 'De-Veined', brand: 'Whole Foods',
        packingStyle: '20 Lbs', freezer: 'IQF -5', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '6°C', coreTempAfterChiller: '4°C',
        supervisor: 'Tom', remarks: 'Sustainable Shrimp',
        productCoreTemp1: F(110, false),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(120, true),
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '6', sampleNumber: '42213', section: 'Temperature', batchInfo: '125-13c-12/14-3214',
        batchNumber: '2026-048269', grade: '12/19', variety: 'EZPL', brand: 'Safeway',
        packingStyle: '5 Lbs', freezer: 'IQF -2', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '8°C', coreTempAfterChiller: '8°C',
        supervisor: 'Lily', remarks: 'Smoked Salmon',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(40,  false),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(120, true),
        status: 'Pass', action: 'Approved',
      },
      {
        key: '7', sampleNumber: '42213', section: 'Temperature', batchInfo: '125-13c-12/14-3214',
        batchNumber: '2026-048270', grade: '12/20', variety: 'FROZEN', brand: "Trader Joe's",
        packingStyle: '12 Lbs', freezer: 'IQF -3', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '3°C', coreTempAfterChiller: '3°C',
        supervisor: 'Kenji', remarks: 'Batch within spec',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(55,  false),
        productCoreTemp5: F(120, true),
        status: 'Fail', action: 'Rejected',
      },
    ],
    'processing': [
      {
        key: '1', sampleNumber: '42301', section: 'Temperature', batchInfo: '136-14c-10/12-1122',
        batchNumber: '2026-049100', grade: '10/12', variety: 'H-Less', brand: 'Costco',
        packingStyle: '6*4 Lbs', freezer: 'IQF -1', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '2°C', coreTempAfterChiller: '2°C',
        supervisor: 'Rahul', remarks: 'Consistent quality',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(120, true),
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', sampleNumber: '42301', section: 'Temperature', batchInfo: '136-14c-10/12-1122',
        batchNumber: '2026-049101', grade: '10/13', variety: 'H-ON', brand: 'Walmart',
        packingStyle: '4*6 Lbs', freezer: 'IQF -2', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '3°C', coreTempAfterChiller: '4°C',
        supervisor: 'Maya', remarks: 'Temp spike detected',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(48,  false),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(120, true),
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3', sampleNumber: '42301', section: 'Temperature', batchInfo: '136-14c-10/12-1122',
        batchNumber: '2026-049102', grade: '10/14', variety: 'H-Less', brand: 'Target',
        packingStyle: '5*4 Lbs', freezer: 'IQF -3', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '1°C', coreTempAfterChiller: '2°C',
        supervisor: 'Jake', remarks: 'Good uniformity',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(52,  false),
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '4', sampleNumber: '42301', section: 'Temperature', batchInfo: '136-14c-10/12-1122',
        batchNumber: '2026-049103', grade: '10/15', variety: 'H-ON', brand: 'Kroger',
        packingStyle: '3*6 Lbs', freezer: 'IQF -4', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '4°C', coreTempAfterChiller: '3°C',
        supervisor: 'Sara', remarks: 'Clean batch',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(120, true),
        status: 'Pass', action: 'Approved',
      },
      {
        key: '5', sampleNumber: '42301', section: 'Temperature', batchInfo: '136-14c-10/12-1122',
        batchNumber: '2026-049104', grade: '10/16', variety: 'De-Veined', brand: 'Whole Foods',
        packingStyle: '7*2 Lbs', freezer: 'IQF -5', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '5°C', coreTempAfterChiller: '5°C',
        supervisor: 'Tom', remarks: 'Sustainable batch',
        productCoreTemp1: F(112, false),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(120, true),
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '6', sampleNumber: '42301', section: 'Temperature', batchInfo: '136-14c-10/12-1122',
        batchNumber: '2026-049105', grade: '10/17', variety: 'EZPL', brand: "Sam's Club",
        packingStyle: '8*4 Lbs', freezer: 'IQF -6', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '2°C', coreTempAfterChiller: '1°C',
        supervisor: 'Laura', remarks: 'Minimal defects',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(120, true),
        status: 'Pass', action: 'Approved',
      },
      {
        key: '7', sampleNumber: '42301', section: 'Temperature', batchInfo: '136-14c-10/12-1122',
        batchNumber: '2026-049106', grade: '10/18', variety: 'H-Less', brand: "Trader Joe's",
        packingStyle: '5*3 Lbs', freezer: 'IQF -7', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '6°C', coreTempAfterChiller: '6°C',
        supervisor: 'Kenji', remarks: 'Premium quality',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(43,  false),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(120, true),
        status: 'Fail', action: 'Rejected',
      },
    ],
    'others': [
      {
        key: '1', sampleNumber: '42401', section: 'Temperature', batchInfo: '150-12c-08/10-2211',
        batchNumber: '2026-050200', grade: '08/10', variety: 'EZPL', brand: 'Costco',
        packingStyle: '6*5 Lbs', freezer: 'IQF -3', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '1°C', coreTempAfterChiller: '2°C',
        supervisor: 'Rahul', remarks: 'Within spec limits',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(120, true),
        status: 'Pass', action: 'Approved',
      },
      {
        key: '2', sampleNumber: '42401', section: 'Temperature', batchInfo: '150-12c-08/10-2211',
        batchNumber: '2026-050201', grade: '08/11', variety: 'FRESH', brand: 'Walmart',
        packingStyle: '4*7 Lbs', freezer: 'IQF -1', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '3°C', coreTempAfterChiller: '3°C',
        supervisor: 'Maya', remarks: 'Loose shell found',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(47,  false),
        productCoreTemp5: F(120, true),
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '3', sampleNumber: '42401', section: 'Temperature', batchInfo: '150-12c-08/10-2211',
        batchNumber: '2026-050202', grade: '08/12', variety: 'FROZEN', brand: 'Target',
        packingStyle: '5*6 Lbs', freezer: 'IQF -2', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '2°C', coreTempAfterChiller: '1°C',
        supervisor: 'Jake', remarks: 'Clean batch',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(120, true),
        status: 'Pass', action: 'Approved',
      },
      {
        key: '4', sampleNumber: '42401', section: 'Temperature', batchInfo: '150-12c-08/10-2211',
        batchNumber: '2026-050203', grade: '08/13', variety: 'FRESH', brand: 'Kroger',
        packingStyle: '3*8 Lbs', freezer: 'IQF -4', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '4°C', coreTempAfterChiller: '4°C',
        supervisor: 'Sara', remarks: 'Good quality',
        productCoreTemp1: F(51,  false),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(120, true),
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '5', sampleNumber: '42401', section: 'Temperature', batchInfo: '150-12c-08/10-2211',
        batchNumber: '2026-050204', grade: '08/14', variety: 'EZPL', brand: 'Whole Foods',
        packingStyle: '7*3 Lbs', freezer: 'IQF -5', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '5°C', coreTempAfterChiller: '3°C',
        supervisor: 'Tom', remarks: 'Minimal defects',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(120, true),
        status: 'Pass', action: 'Approved',
      },
      {
        key: '6', sampleNumber: '42401', section: 'Temperature', batchInfo: '150-12c-08/10-2211',
        batchNumber: '2026-050205', grade: '08/15', variety: 'FROZEN', brand: "Sam's Club",
        packingStyle: '8*2 Lbs', freezer: 'IQF -6', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '7°C', coreTempAfterChiller: '7°C',
        supervisor: 'Laura', remarks: 'Wrong cut found',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(44,  false),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(120, true),
        status: 'Fail', action: 'Rejected',
      },
      {
        key: '7', sampleNumber: '42401', section: 'Temperature', batchInfo: '150-12c-08/10-2211',
        batchNumber: '2026-050206', grade: '08/16', variety: 'EZPL', brand: "Trader Joe's",
        packingStyle: '5*5 Lbs', freezer: 'IQF -7', avgProductCoreTemp: '120°F',
        counterCoolerWaterTemp: '3°C', coreTempAfterChiller: '2°C',
        supervisor: 'Kenji', remarks: 'Premium quality',
        productCoreTemp1: F(120, true),
        productCoreTemp2: F(120, true),
        productCoreTemp3: F(120, true),
        productCoreTemp4: F(120, true),
        productCoreTemp5: F(120, true),
        status: 'Pass', action: 'Approved',
      },
    ],
  },
};

export default TemperatureConfig;
